src/main/java/com/digitalpebble/storm/crawler/CrawlTopology.java
src/main/java/com/digitalpebble/storm/crawler/bolt/FetcherBolt.java
src/main/java/com/digitalpebble/storm/crawler/bolt/ParserBolt.java
src/main/java/com/digitalpebble/storm/crawler/persistence/Status.java

also used by fetcher to report redirections
related to issues  #37 and #38 #42 
implements #43

Fetcher and Parser use the status stream to report errors instead of fail

---

pom.xml

Add myself to the list of contributors

---

src/main/java/com/digitalpebble/storm/crawler/CrawlTopology.java
src/main/java/com/digitalpebble/storm/crawler/bolt/ParserBolt.java

Implements #64 
Could you please review?

ParserBolt uses right Status class + relies on standard metrics

---

core/pom.xml
external/pom.xml
pom.xml

No jar-with-dependencies; no test jar for parent.

Fix maven release profile

---

core/src/main/java/com/digitalpebble/storm/fetchqueue/URLInjector.java

As it is specifically about sharded queues

Moved URLInjector to fetchqueue package

---

core/src/main/java/com/digitalpebble/storm/crawler/protocol/http/HttpProtocol.java
core/src/main/java/com/digitalpebble/storm/crawler/protocol/http/HttpResponse.java

Pass the metadata to HttpResponse

Fix the Concurrency issue with ProtocolFactory

---

external/ES_IndexInit.sh
external/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/bolt/ESCrawlTopology.java
external/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/bolt/ElasticSearchSpout.java

added a script to setup status index and inject a single URL
first working version of ElasticSearchSpout
implements #92

ElasticSearchSpout

---

external/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/bolt/StatusUpdaterBolt.java

Not sure this is right or if I should upgrade to a more recent version of ElasticSearch...

Fix compilation error

---

core/src/main/java/com/digitalpebble/storm/crawler/filtering/basic/BasicURLFilter.java
core/src/main/java/com/digitalpebble/storm/crawler/filtering/regex/RegexURLNormalizer.java
core/src/test/java/com/digitalpebble/storm/crawler/filtering/BasicURLFilterTest.java

Easier to reason about than writing regular expressions to normalize a particular query
parameter.  Handles things like remove the ? if there are no more query parameters.
@jnioche not sure if you'd think this generally useful? I can easily pull into our own project, but would like your feedback anyway :) so started here..
@GuiForget any pointers on java idioms, etc always welcome.

Add a normalizer to remove specified query parameters.

---

core/src/main/java/com/digitalpebble/storm/crawler/filtering/regex/RegexURLFilterBase.java
core/src/main/java/com/digitalpebble/storm/crawler/filtering/regex/RegexURLNormalizer.java

config format:
{
"urlFilters": [
"-^http:\/\/dimg.dillards.com",
"-^http:\/\/www.dillards.com\/webapp"
],
"urlNormalizers": [
{
"pattern": "^(http://www.dillards.com/product/.+)(\?.*)$",
"substitution": "$1"
},
{
"pattern": "somepattern2",
"substitution": "replacement2"
}
]
}

Added support for Json config instead of filename.

---

core/pom.xml
core/src/main/java/com/digitalpebble/storm/crawler/CrawlTopology.java
core/src/main/java/com/digitalpebble/storm/crawler/parse/ParseFilter.java
core/src/test/java/com/digitalpebble/storm/crawler/parse/filter/XPathFilterTest.java
external/pom.xml
external/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/ESCrawlTopology.java
external/src/main/java/com/digitalpebble/storm/crawler/tika/DOMBuilder.java
external/src/main/java/com/digitalpebble/storm/crawler/tika/ParserBolt.java
external/src/main/java/com/digitalpebble/storm/crawler/tika/XMLCharacterRecognizer.java

See #114 
@DigitalPebble/committers-crawler please review and test

Moved Tika parser to external #114

---

core/src/main/java/com/digitalpebble/storm/crawler/bolt/FetcherBolt.java
core/src/main/java/com/digitalpebble/storm/crawler/bolt/SimpleFetcherBolt.java

@jnioche these are useful for monitoring, any thoughts? Would be happy to add some additional refactoring for the commit...several low-hanging fruit where the metrics could be improved

Added bytes fetched and fetch time metrics

---

core/src/main/java/com/digitalpebble/storm/crawler/bolt/JSoupParserBolt.java

+ refactored handling of exceptions
We can improve the checking mechanism later but at least it will prevent non-html documents to be parsed with JSOUP.

JSoupParserBolt does a basic check of the content type

---

external/solr/README.md
external/solr/solr-example-cores/metrics/conf/schema.xml
external/solr/solr-example-cores/metrics/conf/solrconfig.xml
external/solr/solr-example-cores/metrics/core.properties
external/solr/solr-example-cores/parse/conf/schema.xml
external/solr/solr-example-cores/parse/conf/solrconfig.xml
external/solr/solr-example-cores/parse/core.properties
external/solr/solr-example-cores/status/conf/schema.xml
external/solr/solr-example-cores/status/conf/solrconfig.xml
external/solr/solr-example-cores/status/core.properties

A basic README file containing the provided resources, how to use them, and the different configuration parameters available. Issue https://github.com/DigitalPebble/storm-crawler/issues/155
@jnioche Can you take a look?

Adding a README file to the solr module

---

core/src/main/java/com/digitalpebble/storm/crawler/parse/ParseFilter.java
core/src/main/java/com/digitalpebble/storm/crawler/parse/ParseFilters.java
core/src/main/java/com/digitalpebble/storm/crawler/parse/filter/ContentFilter.java
core/src/main/java/com/digitalpebble/storm/crawler/parse/filter/DebugParseFilter.java
core/src/main/java/com/digitalpebble/storm/crawler/parse/filter/XPathFilter.java
core/src/test/java/com/digitalpebble/storm/crawler/parse/filter/SubDocumentsParseFilter.java

ParseFilter from interface to abstract class

---

core/src/main/java/com/digitalpebble/storm/crawler/util/MetadataTransfer.java

A correction of the issue 168.
Thx,
Ludovic.

Correction of a NPE in metadata transfert function

---

external/solr/README.md
external/solr/solr-conf.yaml

Updates the README file to remove some of the outdated info.

Remove outdated configuration options for solr module

---

external/solr/README.md
external/solr/solr-conf.yaml

Cleaning some documentation and typo issues in the solr documentation.

Cleaning some documentation and typo issues

---

external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/ESSeedInjector.java

Comparable to [https://github.com/DigitalPebble/storm-crawler/blob/master/external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/SeedInjector.java]

ESSeedInjector topology

---

external/elasticsearch/ES_IndexInit.sh
external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/ElasticSearchSpout.java
external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/StatusUpdaterBolt.java

ElasticSearch : metadata as structured object. Implements #197

---

core/src/main/java/com/digitalpebble/storm/crawler/Constants.java
core/src/main/java/com/digitalpebble/storm/crawler/persistence/AbstractStatusUpdaterBolt.java
core/src/main/resources/crawler-default.yaml

Change Status to ERROR when FETCH_ERROR above threshold #202

---

external/solr/README.md
external/solr/solr-conf.yaml
external/solr/solr-example-cores/status/conf/schema.xml
external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/persistence/SolrSpout.java
external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/persistence/StatusUpdaterBolt.java

This address issue #207. Also contains an update for the documentation of the Solr module

Updating solr module to store the metadata field as separated fields

---

core/src/main/java/com/digitalpebble/storm/crawler/bolt/FetcherBolt.java
core/src/main/java/com/digitalpebble/storm/crawler/bolt/SimpleFetcherBolt.java
core/src/main/java/com/digitalpebble/storm/crawler/util/PerSecondReducer.java
external/elasticsearch/kibana.json

Used in Fetcher bolts for byte and docs per sec.

PerSecondReducer for Storm metrics + 

---

core/src/main/java/com/digitalpebble/storm/crawler/bolt/FetcherBolt.java

See #45.
If `fetcherbolt.queue.debug.filepath` is set to a non-empty value in the config and a file exists with the same name then the content of the internal queues will be dumped to the log.  The file is deleted straight after generating the dump.
The string '{port}' from the filepath value will be replaced by the actual port value for the worker e.g. `/tmp/fetcher-dump-{port}`. This string is not mandatory, setting a value independent from the port will trigger all workers on a given host to dump the queues, but each in their own log file.

Fetcher to dump the content of its queues to the log #45

---

.gitignore

.DS_Store is just a system file for storing custom folder attributes

Ignore OSX system files

---

core/src/main/java/com/digitalpebble/storm/crawler/persistence/AbstractStatusUpdaterBolt.java
core/src/main/java/com/digitalpebble/storm/crawler/persistence/DefaultScheduler.java
core/src/main/java/com/digitalpebble/storm/crawler/persistence/Scheduler.java
core/src/main/resources/crawler-default.yaml

Scheduler is now an abstract class with a static method for generating an instance based on the configuration. 
This allows users to specify a specific implementation of Scheduler via the config.

Pluggable Schedulers #104

---

external/sql/src/main/java/com/digitalpebble/storm/crawler/sql/SQLSpout.java
external/sql/src/main/java/com/digitalpebble/storm/crawler/sql/StatusUpdaterBolt.java

This pull request is focused on resolving occurrences of Sonar rule squid:S2095 - “ Resources should be closed”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S2095

 Resources should be closed

---

core/src/main/java/com/digitalpebble/storm/crawler/bolt/FetcherBolt.java
core/src/main/java/com/digitalpebble/storm/crawler/bolt/SimpleFetcherBolt.java
core/src/main/java/com/digitalpebble/storm/crawler/bolt/SiteMapParserBolt.java
core/src/main/java/com/digitalpebble/storm/crawler/filtering/regex/RegexURLFilterBase.java
core/src/main/java/com/digitalpebble/storm/crawler/parse/JSoupDOMBuilder.java
core/src/main/java/com/digitalpebble/storm/crawler/persistence/Scheduler.java
core/src/main/java/com/digitalpebble/storm/crawler/protocol/ProtocolFactory.java
core/src/main/java/com/digitalpebble/storm/crawler/protocol/RobotRulesParser.java
core/src/main/java/com/digitalpebble/storm/crawler/util/MetadataTransfer.java
external/tika/src/main/java/com/digitalpebble/storm/crawler/tika/ParserBolt.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1854 - “ Dead stores should be removed ”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1854

Dead stores should be removed

---

core/src/main/java/com/digitalpebble/storm/crawler/persistence/AbstractStatusUpdaterBolt.java
external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/StatusUpdaterBolt.java

Cleaner version of #241, implements #216
Decoupled acking of tuples in AbstractStatusUpdaterBolt + ES StatusUpdaterBolt now properly acks tuples after they've been sent to ES or failed in case of failure.
This prevents URLs from being excessively replayed by the ES spout. They were acked before being actually sent to ES, removed from the cache in the spout then refetched immediately as their status had not been changed.
You will get a warning "Already sent to ES" if a URL is found while another tuple with the same URL is being sent to ES. This usually means that a webpage contains a link to itself which hasn't been filtered out - see #252

AbstractStatusUpdaterBolt allow proper acking of tuples

---

external/elasticsearch/es-conf.yaml
external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/AggregationSpout.java

Implements ES AggregationSpout sort buckets by oldest nextFetchDate #270

Aggreg spout sorted buckets

---

core/src/main/java/com/digitalpebble/storm/crawler/parse/filter/LinkParseFilter.java
core/src/main/java/com/digitalpebble/storm/crawler/parse/filter/XPathFilter.java

@mattburns  do you want to be a guinea pig and give this a try?

Allow other links to be considered outlinks #267

---

external/elasticsearch/ES_IndexInit.sh
external/elasticsearch/es-conf.yaml
external/elasticsearch/pom.xml
external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/ElasticSearchConnection.java
external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/AggregationSpout.java
external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/ElasticSearchSpout.java
external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/StatusUpdaterBolt.java

Based on #257, uses ES 2.3.1
The only limitation is that the node client does not work for now, but the transport one does.
@w0mbat thanks for your work on #257 - I've built a new branch but yours was a great starting point. Any chance you could give this one a try?

Update to Elasticsearch 2.x

---

core/src/main/java/com/digitalpebble/storm/crawler/bolt/FetcherBolt.java

Provide a real loop in FetchItemQueues in order to rotate completly the map and not restart a the begin on each new entry

FetcherBolt : real loop in FetchItemQueues in order to rotate completly the map 

---

core/pom.xml
core/src/main/java/com/digitalpebble/storm/crawler/bolt/FeedParserBolt.java
core/src/test/java/com/digitalpebble/storm/crawler/bolt/FeedParserBoltTest.java
core/src/test/resources/guardian.rss

Similar to the SitemapParser bolt but this time for feeds. See #284
comments and reviews welcome as usual

Added bolt for parsing RSS feeds 

---

core/src/main/java/com/digitalpebble/storm/crawler/bolt/FetcherBolt.java

See  #278
Now that we are on Storm 1.x the original restriction that the collector had to be accessed from the main thread has disappeared. This simplifies the code a lot and removes the need for a tick tuple.

FetcherBolt simplify access to OutputCollector

---

external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/ElasticSearchConnection.java

Flush BulkProcessor before closing connection

---

external/elasticsearch/ES_IndexInit.sh
external/elasticsearch/README.md
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/metrics/IndexPerDayMetricsConsumer.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/metrics/IndexPerMonthMetricsConsumer.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/metrics/IndexPerPeriodMetricsConsumer.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/metrics/MetricsConsumer.java

Hi Julien, I think I've addressed the headers, etc, that we discussed. Let me know if there's anything else.

Per day metrics indices

---

core/src/main/java/com/digitalpebble/stormcrawler/bolt/SimpleFetcherBolt.java

Addresses some issues where the fetch.exception gets written as the hostname rather than the actual error that occurred.

Fetch exception improvements

---

core/src/main/java/com/digitalpebble/stormcrawler/persistence/DefaultScheduler.java
core/src/main/java/com/digitalpebble/stormcrawler/persistence/MemoryStatusUpdater.java
core/src/test/java/com/digitalpebble/stormcrawler/persistence/DefaultSchedulerTest.java

- final never-refetch date 2099-12-31

Fix for #337 ES error when parsing never refetch date

---

core/src/main/java/com/digitalpebble/stormcrawler/bolt/SimpleFetcherBolt.java

Removing politeness from robots denial

---

external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AbstractSpout.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AggregationSpout.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/ElasticSearchSpout.java

Implements #347 
FYI @sebastian-nagel

Refactoring into AbstractSpout for ES

---

core/src/main/java/com/digitalpebble/stormcrawler/bolt/JSoupParserBolt.java
core/src/main/java/com/digitalpebble/stormcrawler/util/RefreshTag.java
core/src/test/java/com/digitalpebble/stormcrawler/bolt/JSoupParserBoltTest.java
core/src/test/resources/redir.html

Handle redirections via meta tag, implements #350

---

external/warc/README.md
external/warc/pom.xml
external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/GzipHdfsBolt.java
external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCFileNameFormat.java
external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCHdfsBolt.java
external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCRecordFormat.java
external/warc/src/test/java/com/digitalpebble/stormcrawler/warc/WARCRecordFormatTest.java
pom.xml

Moved code and resources from [https://github.com/DigitalPebble/sc-warc]

Moved WARC module to main repo, fixes #313

---

external/langid/pom.xml
external/langid/src/main/java/com/digitalpebble/stormcrawler/parse/filter/LanguageID.java
pom.xml

Language Identification Module

---

external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/bolt/IndexerBolt.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/StatusUpdaterBolt.java

ES: use SHA256 as doc_id

---

core/src/main/java/com/digitalpebble/stormcrawler/bolt/SimpleFetcherBolt.java

SimpleFetcherBolt: do not overwrite fetch.StatusCode and fetch.loadingTime with persisted values

---

archetype/src/main/resources/archetype-resources/crawler-conf.yaml
core/src/main/java/com/digitalpebble/stormcrawler/persistence/DefaultScheduler.java
core/src/main/resources/crawler-default.yaml

Fixes #420 
We don't expect the entries to be in any particular order and the behaviour should now be deterministic.
@sebastian-nagel could you please have a look and test?

custom scheduling is now deterministic

---

core/src/main/java/com/digitalpebble/stormcrawler/protocol/file/FileProtocol.java
core/src/main/java/com/digitalpebble/stormcrawler/protocol/file/FileResponse.java
core/src/main/resources/crawler-default.yaml

[#435](https://github.com/DigitalPebble/storm-crawler/issues/435) I have adopted Apache Nutch File Protocol to Storm Crawler. I have removed some headers in Nutch. I need your advice to provide better file protocol.

File protocol implementation #435

---

core/src/main/java/com/digitalpebble/stormcrawler/Constants.java
core/src/main/java/com/digitalpebble/stormcrawler/persistence/AbstractStatusUpdaterBolt.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/ESCrawlTopology.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/bolt/DeletionBolt.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/bolt/IndexerBolt.java

Delete gone pages from index, fixes #253

---

core/pom.xml
core/src/main/java/com/digitalpebble/stormcrawler/bolt/SiteMapParserBolt.java

Upgrade to Crawler-Commons 0.8

---

external/sql/sql-conf.yaml
external/sql/src/main/java/com/digitalpebble/stormcrawler/sql/SQLSpout.java
external/sql/src/main/java/com/digitalpebble/stormcrawler/sql/StatusUpdaterBolt.java
external/sql/tableCreation.script

- Added logs and metrics to SQLSpout
- SQL table renamed to urls + added indices and column host

Sqlspoutstats

---

external/elasticsearch/es-conf.yaml
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AbstractSpout.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AggregationSpout.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/CollapsingSpout.java

@owenrh the same logic should be applicable to your custom spout implementation

Configurable filters for ES spouts, fixes #502

---

core/src/main/java/com/digitalpebble/stormcrawler/protocol/file/FileResponse.java
core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
core/src/main/java/com/digitalpebble/stormcrawler/protocol/selenium/SeleniumProtocol.java

okhttp : store request and response headers verbatim in metadata

---

pom.xml

Update the contact information on the `pom.xml` file.

Update contributor information

---

core/src/main/java/com/digitalpebble/stormcrawler/parse/ParseFilter.java
external/elasticsearch/ES_IndexInit.sh
external/elasticsearch/pom.xml
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/ElasticSearchConnection.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/metrics/StatusMetricsBolt.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AggregationSpout.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/CollapsingSpout.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/StatusUpdaterBolt.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/util/URLExtractor.java

Fixes #516 
contains a minor unrelated change which has been put there by mistake but no big deal

Upgrade to ES 6.0

---

archetype/src/main/resources/archetype-resources/crawler-conf.yaml
core/src/main/java/com/digitalpebble/stormcrawler/parse/filter/LinkParseFilter.java
core/src/main/resources/crawler-default.yaml
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/ESSeedInjector.java
external/solr/src/main/java/com/digitalpebble/stormcrawler/solr/SeedInjector.java

Fix parameter name to pass config file to ConfigurableTopology

---

core/src/main/resources/crawler-default.yaml

Increase detect.charset.maxlength default value #537

---

core/src/main/java/com/digitalpebble/stormcrawler/bolt/JSoupParserBolt.java
core/src/main/java/com/digitalpebble/stormcrawler/util/RefreshTag.java
core/src/main/java/com/digitalpebble/stormcrawler/util/RobotsTags.java

See #562 
Added methods to RefreshTag and RobotsTags to normalise string values, which are extracted with the select methods of jsoup.

JSOUPParserBolt: lazy DOM conversion, fixes #562

---

external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/metrics/StatusMetricsBolt.java

In order to avoid NPE when there is an exception when doing  a multisearch request in StatusMetricsBolt.
We added an extra check in order to guarantee that response is not null.
As you can see in ES java doc of `MultiSearchResponse.Item` class getResponse() may be null
```
/**
* The actual search response, null if its a failure.
*/
@Nullable
public SearchResponse getResponse() {
return this.response;
}
```

StatusMetricsBolt - Added check for avoid NPE when interacting with multi search response

---

core/src/main/java/com/digitalpebble/stormcrawler/persistence/AbstractStatusUpdaterBolt.java
core/src/main/resources/crawler-default.yaml

Scheduling -> round to the closest second, minute or hour, fixes #654

---

core/src/main/java/com/digitalpebble/stormcrawler/persistence/AbstractQueryingSpout.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AggregationSpout.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/CollapsingSpout.java

Asynchronous spouts (i.e ES) can send queries after max delay since previous one ended

---

external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/bolt/IndexerBolt.java

ES IndexerBolt : check success of batches before acking tuples

---

core/src/main/java/com/digitalpebble/stormcrawler/persistence/AbstractStatusUpdaterBolt.java
core/src/main/java/com/digitalpebble/stormcrawler/persistence/MemoryStatusUpdater.java
core/src/main/java/com/digitalpebble/stormcrawler/persistence/StdOutStatusUpdater.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/StatusUpdaterBolt.java
external/solr/src/main/java/com/digitalpebble/stormcrawler/solr/persistence/StatusUpdaterBolt.java
external/sql/src/main/java/com/digitalpebble/stormcrawler/sql/StatusUpdaterBolt.java

changed ack mechanism for status updater bolts, fixes #689

---

core/src/main/java/com/digitalpebble/stormcrawler/bolt/URLFilterBolt.java
external/elasticsearch/ES_IndexInit.sh
external/elasticsearch/es-conf.yaml
external/elasticsearch/pom.xml
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/ElasticSearchConnection.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/bolt/DeletionBolt.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/bolt/IndexerBolt.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/filtering/JSONURLFilterWrapper.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/metrics/MetricsConsumer.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/metrics/StatusMetricsBolt.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/parse/filter/JSONResourceWrapper.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AbstractSpout.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AggregationSpout.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/CollapsingSpout.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/StatusUpdaterBolt.java

Upgrade to Elasticsearch 7.0.x 

---

external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AggregationSpout.java

Fixing issue related due SDF not thread-safe

#809 - Fixing issue with SDF not thread safe

---

core/src/main/java/com/digitalpebble/stormcrawler/JSONResource.java
core/src/main/java/com/digitalpebble/stormcrawler/bolt/JSoupParserBolt.java
core/src/main/java/com/digitalpebble/stormcrawler/jsoup/LDJsonParseFilter.java
core/src/main/java/com/digitalpebble/stormcrawler/parse/JSoupFilter.java
core/src/main/java/com/digitalpebble/stormcrawler/parse/JSoupFilters.java
core/src/main/java/com/digitalpebble/stormcrawler/parse/filter/LDJsonParseFilter.java
core/src/test/java/com/digitalpebble/stormcrawler/json/JsoupFilterTest.java
core/src/test/resources/test.jsoupfilters.json

Jsoupfilters

---

core/src/main/java/com/digitalpebble/stormcrawler/protocol/AbstractHttpProtocol.java
core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java
core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
core/src/main/java/com/digitalpebble/stormcrawler/proxy/MultiProxyManager.java
core/src/main/java/com/digitalpebble/stormcrawler/proxy/ProxyManager.java
core/src/main/java/com/digitalpebble/stormcrawler/proxy/SingleProxyManager.java
core/src/test/java/com/digitalpebble/stormcrawler/proxy/MultiProxyManagerTest.java
core/src/test/java/com/digitalpebble/stormcrawler/proxy/SingleProxyManagerTest.java

```
Version 1.1
Suite D4700
By making a …
```

Proxy bug fix

---

core/src/main/java/com/digitalpebble/stormcrawler/bolt/FetcherBolt.java
core/src/main/java/com/digitalpebble/stormcrawler/bolt/StatusEmitterBolt.java

Fixes #884
Was a workaround for an issue since fixed in Storm

removed sync in statusemitterbolt

---

core/src/main/java/com/digitalpebble/stormcrawler/bolt/JSoupParserBolt.java

Signed-off-by: Julian Alvarez <juli.alvarez92@gmail.com>
```
Version 1.1
Suite D4700 …
```

ISSUE-928: added flag to ignore meta redirections in jsoup bolt

---

core/src/main/java/com/digitalpebble/stormcrawler/bolt/FetcherBolt.java
core/src/main/java/com/digitalpebble/stormcrawler/bolt/JSoupParserBolt.java

Changed order of emit outlinks and emit of parent url when redirections happens in fetcher bolt.
Signed-off-by: Julian Alvarez <juli.alvarez92@gmail.com>
```
Version 1.1
Suite D4700
Everyone is permitted …
```

ISSUE-954: Issue with the order of emit and emitOutlink for redirections in FetcherBolt

---

core/src/main/java/com/digitalpebble/stormcrawler/bolt/FetcherBolt.java

Signed-off-by: Julian Alvarez <juli.alvarez92@gmail.com>
```
Version 1.1
Suite D4700 …
```

FEATURE-964: custom crawl delay per page

---

core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java

```
Version 1.1
Suite D4700
By making a …
```

Issue 970 HttpProtocol doesn't consider http.content.limit in test for filesize

---

core/src/main/java/com/digitalpebble/stormcrawler/jsoup/LDJsonParseFilter.java
core/src/main/java/com/digitalpebble/stormcrawler/jsoup/XPathFilter.java
core/src/main/java/com/digitalpebble/stormcrawler/parse/JSoupFilter.java
core/src/main/java/com/digitalpebble/stormcrawler/parse/JSoupFilters.java
core/src/main/java/com/digitalpebble/stormcrawler/util/Configurable.java
core/src/main/java/com/digitalpebble/stormcrawler/util/ConfigurableHelper.java

Hi @jnioche ! 
This PR is related to https://github.com/DigitalPebble/storm-crawler/pull/1002 .
The `JsoupFilter` abstract class become an interface. It's provide us a better architecture for our other filter bolt (see https://github.com/DigitalPebble/storm-crawler/pull/1002).
Our topologies are already running with a `JsoupBolt` fork and `JsoupFilter` as interface and all works fine for a few month, so we are glad to share it.
For all other homemade filter, users have to change the class declaration :
```
public class MyFilter extends JSoupFilter {
```
into 
```
public class MyFilter extends AbstractConfigurable implements JSoupFilter {
```
Developer Certificate of …

JsoupFilter as Interface

---

core/src/main/java/com/digitalpebble/stormcrawler/persistence/AbstractStatusUpdaterBolt.java
external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/StatusUpdaterBolt.java
external/opensearch/src/main/java/com/digitalpebble/stormcrawler/opensearch/persistence/StatusUpdaterBolt.java

Hi ! 
Our topologies are running every day with the same URLs. So, each day, the same links are discovered. We want to keep all discovered links throught the days (to analyze for example). We create a `getDocumentId()` in `StatusUpdaterBolt()`  to set a random UUID (as https://github.com/DigitalPebble/storm-crawler/pull/1028).
Thanks ! :)
Please refer to the *Developer Certificate of Origin* section in …

Status ES document id

---

core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java
core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java

Hi ! 
As already discussed (https://github.com/DigitalPebble/storm-crawler/pull/1040), we want to override `addHeadersToRequest`.
```
Version 1.1
Suite D4700
San Francisco, CA, …
```

Allow override on HttpProtocol's method addHeadersToRequest

---

core/pom.xml

```
Version 1.1
Suite D4700
By making a …
```

Fixes #1045. Remove range syntax from snakeyaml

---

core/src/main/java/com/digitalpebble/stormcrawler/protocol/selenium/RemoteDriverProtocol.java

```
Version 1.1
Suite D4700
By making a …
```

Fix #1032: Catch the exception inside the loop to avoid breaking if one remote instance is misbehaving

---

core/src/main/java/com/digitalpebble/stormcrawler/protocol/selenium/RemoteDriverProtocol.java
core/src/main/resources/crawler-default.yaml

refactoring timeouts Selenium

---

external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AggregationSpout.java
external/opensearch/src/main/java/com/digitalpebble/stormcrawler/opensearch/persistence/AggregationSpout.java

With the wrong potentialNewDate was assigned, it was always 1970-xx-xx.

Fix wrong most recent date was set

---

pom.xml

Add committer statement

---

core/pom.xml
external/opensearch/pom.xml
external/warc/pom.xml
pom.xml

dependency upgrades

---

pom.xml

Fixes #1179 
Also changed the link for the project. Will change it again when the project has a proper website.

Removed devs section from pom.xml

---

archetype/pom.xml
core/pom.xml
external/aws/pom.xml
external/langid/pom.xml
external/opensearch/archetype/pom.xml
external/opensearch/pom.xml
external/pom.xml
external/solr/pom.xml
external/sql/pom.xml
external/tika/pom.xml
external/urlfrontier/pom.xml
external/warc/pom.xml
pom.xml

as the title says.
closes #1178

Fixes #1178 "Set version to 3.0-SNAPSHOT"

---

CONTRIBUTING.md

Fix #1168 - Add a modified version of CONTRIBUTING.md

---

.github/PULL_REQUEST_TEMPLATE.md

Fix #1163 - Change the GitHub templates for PRs to be more ASF specific

---

external/opensearch/opensearch-conf.yaml
external/opensearch/src/main/java/org/apache/stormcrawler/opensearch/OpenSearchConnection.java

- [] Have you written or updated unit tests to verify your changes?

#1197 - Allow to disable SSL/TLS verification in OpenSearchConnection

---

README.md
core/src/test/java/org/apache/stormcrawler/protocol/selenium/ProtocolTest.java

This addresses the container emulation issue referenced in #1209 

#1209 fix for emulation error in tests run on silicon

---

external/opensearch/src/main/java/org/apache/stormcrawler/opensearch/Constants.java

https://github.com/apache/incubator-stormcrawler/issues/1211

Resolves #1211 "Fix License Header"

---

README.md

#1205 update archetype in README

---

.asf.yaml

see https://github.com/apache/pekko-http/pull/551

send email if CI build fails

---

RELEASING.md

- Move Source before Maven
- Add Checklist

Fixes #1214 - "Update Release Docs with Feedback from 3.0 RC2 Vote"

---

README.md
archetype/pom.xml
core/pom.xml
external/aws/pom.xml
external/langid/pom.xml
external/opensearch/archetype/pom.xml
external/opensearch/pom.xml
external/pom.xml
external/solr/pom.xml
external/sql/pom.xml
external/tika/pom.xml
external/urlfrontier/pom.xml
external/warc/pom.xml
pom.xml

https://lists.apache.org/thread/88nkdyb3dcblxof16pszom9tqtsdhf3x

Apache StormCrawler 3.0 (Incubating)

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
core/src/test/java/org/apache/stormcrawler/spout/FileSpoutTest.java
core/src/test/java/org/apache/stormcrawler/spout/mocks/FileSpoutOutputCollectorMock.java
core/src/test/java/org/apache/stormcrawler/spout/mocks/FileSpoutTopologyContextMock.java
core/src/test/resources/seed-list-custom-metadata.txt
core/src/test/resources/seed-list-default.txt

Fix #1226 "Add FileSpout TestCase for Custom Metadata Injections"

---

DISCLAIMER-BINARIES.txt

#1220 - Add disclaimer for binary test artifacts

---

RELEASING.md

#1222 - Fix Release Docs

---

external/solr/src/test/java/org/apache/stormcrawler/solr/persistence/IndexerBoltTest.java
external/solr/src/test/java/org/apache/stormcrawler/solr/persistence/SolrContainerTest.java
external/solr/src/test/java/org/apache/stormcrawler/solr/persistence/StatusBoltTest.java

The changes from #1240 were merged into branch apache:851 but not into main. This PR merges the changes from apache:851.

#851 Merge branch 851 into main

---

.github/dependabot.yml

#1259 - Enable Dependabot

---

.github/workflows/main.yml

…flow.
We use a similar approach in TomEE for BOM files. It works quite fine.

#1261 - Automatically generate THIRD-PARTY.txt via GitHub Action

---

pom.xml

#1257 - Update to Storm 2.6.4

---

core/src/main/java/org/apache/stormcrawler/bolt/FeedParserBolt.java
core/src/main/java/org/apache/stormcrawler/bolt/JSoupParserBolt.java
core/src/main/java/org/apache/stormcrawler/bolt/SiteMapParserBolt.java
core/src/main/java/org/apache/stormcrawler/parse/ParseFilter.java
core/src/main/java/org/apache/stormcrawler/parse/ParseFilters.java
core/src/test/java/org/apache/stormcrawler/bolt/AbstractFetcherBoltTest.java
external/tika/src/main/java/org/apache/stormcrawler/tika/ParserBolt.java

Fix #1290 "Add close/cleanup method to ParseFilters"

---

pom.xml

This reverts commit 82c95eb48a67c367c23fbf719fd7511250b237c9.

Revert "Bump log4j2.version from 2.23.0 to 2.24.0"

---

archetype/pom.xml
core/pom.xml
external/aws/pom.xml
external/langid/pom.xml
external/opensearch/archetype/pom.xml
external/opensearch/pom.xml
external/playwright/pom.xml
external/pom.xml
external/solr/pom.xml
external/sql/pom.xml
external/tika/pom.xml
external/urlfrontier/pom.xml
external/warc/pom.xml
pom.xml

Release 3.1.0

---

pom.xml

#1299 - Add DISCLAIMER to JAR files

---

pom.xml

#1300 - Fix "files in jars have odd dates"

---

archetype/src/main/resources/archetype-resources/pom.xml
external/opensearch/archetype/src/main/resources/archetype-resources/pom.xml

#1323 Update archetype Storm version from 2.6.4

---

core/src/main/java/org/apache/stormcrawler/parse/ParseFilter.java
core/src/main/java/org/apache/stormcrawler/parse/filter/CollectionTagger.java
core/src/main/java/org/apache/stormcrawler/util/URLUtil.java
external/solr/src/main/java/org/apache/stormcrawler/solr/bolt/DeletionBolt.java

#1354 Fix: fix some typos in project

---

RELEASING.md
core/src/main/java/org/apache/stormcrawler/parse/filter/CollectionTagger.java

Fix #1312 "Sha512 hash of source release is missing the file part "

---

external/opensearch/archetype/src/main/resources/archetype-resources/opensearch-conf.yaml
external/opensearch/opensearch-conf.yaml
external/opensearch/src/main/java/org/apache/stormcrawler/opensearch/OpenSearchConnection.java
external/opensearch/src/main/java/org/apache/stormcrawler/opensearch/filtering/JSONURLFilterWrapper.java
external/opensearch/src/main/java/org/apache/stormcrawler/opensearch/metrics/MetricsConsumer.java
external/opensearch/src/main/java/org/apache/stormcrawler/opensearch/persistence/AggregationSpout.java
external/opensearch/src/main/java/org/apache/stormcrawler/opensearch/persistence/HybridSpout.java
external/opensearch/src/main/java/org/apache/stormcrawler/opensearch/persistence/StatusUpdaterBolt.java
external/opensearch/src/test/java/org/apache/stormcrawler/opensearch/bolt/IndexerBoltTest.java

Removes some of the references, there might be more hiding in various places

Remove references to ES in OpenSearch module

---

README.md

#1301 - add build doc for the source release

---

external/warc/src/main/java/org/apache/stormcrawler/warc/MetadataRecordFormat.java

[1385] bugfix - check for null before the for-each loop

---

external/opensearch/archetype/src/main/resources/archetype-resources/opensearch-conf.yaml
external/opensearch/opensearch-conf.yaml
external/opensearch/src/main/java/org/apache/stormcrawler/opensearch/OpenSearchConnection.java

- [ x] Is there a issue associated with this PR? Is it referenced in the commit message?
- [ x] Does your PR title start with `#XXXX` where `XXXX` is the issue number you are trying to resolve? 
- [ x] Has your PR been rebased against the latest commit within the target branch (typically main)?
- [ x] Is your initial contribution a single, squashed commit?
- [ x] Is the code properly formatted with `mvn git-code-format:format-code -Dgcf.globPattern="**/*" -Dskip.format.code=false`?
- [ x] Have you ensured that the full suite of tests is executed via `mvn clean verify`?
Please ensure that once the PR is submitted, you check …

Detect multi addresses separated by ; in a single String. Fixes #1382

---

assembly.xml

#1409 - remove <component/> wrapper element

---

.github/dependabot.yml

Prevent Dependabot from suggesting dependency updates for Jackson

---

core/src/test/java/org/apache/stormcrawler/bolt/FeedParserBoltTest.java
core/src/test/java/org/apache/stormcrawler/bolt/JSoupParserBoltTest.java
core/src/test/java/org/apache/stormcrawler/bolt/SiteMapParserBoltTest.java
core/src/test/java/org/apache/stormcrawler/indexer/BasicIndexingTest.java
core/src/test/java/org/apache/stormcrawler/json/JsoupFilterTest.java
core/src/test/java/org/apache/stormcrawler/jsoup/JSoupFiltersTest.java
core/src/test/java/org/apache/stormcrawler/parse/DuplicateLinksTest.java
core/src/test/java/org/apache/stormcrawler/parse/StackOverflowTest.java
core/src/test/java/org/apache/stormcrawler/parse/filter/CSVMetadataFilterTest.java
core/src/test/java/org/apache/stormcrawler/parse/filter/SubDocumentsFilterTest.java
core/src/test/java/org/apache/stormcrawler/parse/filter/XPathFilterTest.java
core/src/test/resources/stormcrawler.apache.org.html
external/tika/src/test/java/org/apache/stormcrawler/tika/ParserBoltTest.java

Some `stormcrawler.apache.org.com` addresses. I've also changed the stormcrawler http URLs to https just for tidiness.

[MINOR] update URLs in tests

---

archetype/pom.xml
core/pom.xml
external/aws/pom.xml
external/langid/pom.xml
external/opensearch/archetype/pom.xml
external/opensearch/pom.xml
external/playwright/pom.xml
external/pom.xml
external/solr/archetype/pom.xml
external/solr/pom.xml
external/sql/pom.xml
external/tika/pom.xml
external/urlfrontier/pom.xml
external/warc/pom.xml
pom.xml

Rel stormcrawler 3.2.0 rc3

---

external/solr/README.md

Remove reference to SNAPSHOT in Solr readme

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
RELEASING.md

fix(docs, lint): Fixed broken image in README, updated official site link, and resolved major lint issues across the repository  

---

archetype/pom.xml
core/pom.xml
external/aws/pom.xml
external/langid/pom.xml
external/opensearch/archetype/pom.xml
external/opensearch/pom.xml
external/playwright/pom.xml
external/pom.xml
external/solr/archetype/pom.xml
external/solr/pom.xml
external/sql/pom.xml
external/tika/pom.xml
external/urlfrontier/pom.xml
external/warc/pom.xml
pom.xml

Rel stormcrawler 3.3.0 rc1

---

README.md
archetype/src/main/resources/archetype-resources/pom.xml
external/opensearch/archetype/src/main/resources/archetype-resources/pom.xml
external/solr/archetype/src/main/resources/archetype-resources/pom.xml
pom.xml

Fixes the comments raised during last release.

Update README and compiler target to Java 17 in several plugins

---

external/opensearch/opensearch-conf.yaml
external/opensearch/src/main/java/org/apache/stormcrawler/opensearch/OpenSearchConnection.java

 #1516 - Add config options to change the response buffer size in OpenSearch

---

NOTICE

Fixes Update NOTICE File to Reflect 2025 

---

RELEASING.md
core/pom.xml
external/opensearch/pom.xml
external/urlfrontier/pom.xml

…docs to mention, that docker needs to be working.

#1298 - Re-enable hold on failure (on coverage fail)

---

README.md
RELEASING.md
external/opensearch/README.md
external/solr/README.md
external/warc/README.md

Fix versions of SC in the READMEs + added instructions in RELEASING

---

archetype/pom.xml
core/pom.xml
external/ai/pom.xml
external/aws/pom.xml
external/langid/pom.xml
external/opensearch/archetype/pom.xml
external/opensearch/pom.xml
external/playwright/pom.xml
external/pom.xml
external/selenium/pom.xml
external/solr/archetype/pom.xml
external/solr/pom.xml
external/sql/pom.xml
external/tika/pom.xml
external/urlfrontier/pom.xml
external/warc/pom.xml
pom.xml

as the title says. Currently under VOTE:

Release StormCrawler 3.5.0
