apache/stormcrawler

- src/main/java/com/digitalpebble/storm/crawler/bolt/ParserBolt.java
- src/main/java/com/digitalpebble/storm/crawler/parse/ParseFilter.java
- src/main/java/com/digitalpebble/storm/crawler/parse/ParseFilters.java
- src/main/java/com/digitalpebble/storm/crawler/parse/filter/DebugParseFilter.java
- src/main/java/com/digitalpebble/storm/crawler/parse/filter/XPathFilter.java
A ParseFilter may want to access the Storm config during its config phase. To
that end the interface is changed to receive both the Storm config as well as
the Filter's parameters.
Also I changed ParseFilters to always call configure on the ParseFilter even
if there are no params defined. I think the original difference was too subtle
and therefore error prone. To make it easy on the ParseFiler, the paramsNode
is set to a NullNode.
Fixes #56
> Pass in the Storm config when configuring ParseFilters

- src/main/java/com/digitalpebble/storm/crawler/bolt/ParserBolt.java
- src/main/java/com/digitalpebble/storm/crawler/parse/DOMBuilder.java
- src/test/java/com/digitalpebble/storm/crawler/parse/filter/XPathFilterTest.java
When parsing the content, Tika creates a properly formatted XHTML document:
all elements are created within the namespace XHTML.
However in XPath 1.0, there's no concept of default namespace so
XPath expressions such as //BODY doesn't match anything. To make this
work we should use //ns1:BODY and define a NamespaceContext which associates
ns1 with "http://www.w3.org/1999/xhtml"
To keep the XPathExpressions simpler, I modified the DOMBuilder which
is our SaxHandler used to convert the SAX Events into a DOM tree to
ignore a "default name space" and the ParserBolt initializes it with
the XHTML namespace. This way //BODY matches.
Fixes #31
> Fix XPathFilter to properly process XPathExpressions with element names

- core/src/main/java/com/digitalpebble/storm/crawler/Constants.java
- core/src/main/java/com/digitalpebble/storm/crawler/bolt/ParserBolt.java
- core/src/main/java/com/digitalpebble/storm/crawler/filtering/URLFilters.java
- Add a boolean to skip the emit of outlinks
- wrap the parseFilters within a try/catch
Note that one subtle change I made is that if we fail to build a URL object
out of the url String, we simply skip the outlinks emitting. The comment
hints toward this not be possible so I don't think that's an issue
> Update to the ParserBolt

- core/src/main/java/com/digitalpebble/storm/crawler/util/URLPartitioner.java
- external/external-conf.yaml
- external/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/ElasticSearchSpout.java
The config `es.status.max.inflight.urls.per.bucket` allows to skip URLs in ESSpout's internal queue if there are already N values being processed for a given key (e.g. hostname, domain, IP). These URLs will be retried when the spout gets the search results from ES to populate the internal queue.
This is used to guarantee a good diversity of sources for the URLs to fetch. The value should be <= topology.max.spout.pending which still takes precedence.
> Throttling in ElasticSearchSpout

- core/src/main/java/com/digitalpebble/storm/crawler/bolt/ParserBolt.java
Tika shouldn't limit content size. It's already done using http.content.limit property.
> Removed write limit from Tika handler to get full text

- core/src/main/java/com/digitalpebble/storm/crawler/filtering/basic/BasicURLNormalizer.java
- core/src/test/java/com/digitalpebble/storm/crawler/filtering/BasicURLNormalizerTest.java
URL encoding is so tricky! And there are basically no good library
that handles it properly, mostly because of the lack of proper support
via the URL and URI classes.
In any event, I rewrote filterQueryElements so that it no longer
double encode the URLs. This is done by simply only modifying the
query string and leaving the other elements unchanged.
I added some 2 unit tests to validate my code.
Fixes #118
> Rewrite BasicURLNormalizer so URLs don't get double encoded

- core/src/main/java/com/digitalpebble/storm/crawler/bolt/FetcherBolt.java
We want to have a default number of max threads to use per queue but also specify arbitrary values per queue ID e.g. `fetcher.maxThreads.INSERT_HOSTNAME_HERE: 10`
This patch also simplifies the queueIDs by not prefixing them with the protocol.
> [Fetcher] Specify arbitraty max thread nums per queue ID

- core/src/main/java/com/digitalpebble/storm/crawler/filtering/depth/MaxDepthFilter.java
- core/src/main/resources/urlfilters.json
This filter will return null if the depth of the URL is > the maxDepth 
parameter. Not setting the maxDepth or setting it to 0 means no limit.
If the depth is not tracked, this filter will do nothing.
> Adding MaxDepthFilter class

- pom.xml
The command `mvn java-formatter:format` will apply the formatting to the code using the Eclipse formatting provided.
The latter can be imported directly in Eclipse and there seems to be plugins for other editors, however the point here is that the formatting will be done regardless of which editor is used.
> maven-java-formatter-plugin

- core/src/main/java/com/digitalpebble/storm/crawler/bolt/JSoupParserBolt.java
- core/src/main/java/com/digitalpebble/storm/crawler/bolt/SiteMapParserBolt.java
- core/src/main/java/com/digitalpebble/storm/crawler/parse/ParseData.java
- core/src/main/java/com/digitalpebble/storm/crawler/parse/ParseFilter.java
- core/src/main/java/com/digitalpebble/storm/crawler/parse/ParseFilters.java
- core/src/main/java/com/digitalpebble/storm/crawler/parse/ParseResult.java
- core/src/main/java/com/digitalpebble/storm/crawler/parse/filter/DebugParseFilter.java
- core/src/main/java/com/digitalpebble/storm/crawler/parse/filter/XPathFilter.java
- core/src/test/java/com/digitalpebble/storm/crawler/parse/filter/SubDocumentsFilterTest.java
- core/src/test/java/com/digitalpebble/storm/crawler/parse/filter/SubDocumentsParseFilter.java
- core/src/test/resources/test.subdocfilter.json
- external/src/main/java/com/digitalpebble/storm/crawler/tika/ParserBolt.java
This address the https://github.com/DigitalPebble/storm-crawler/issues/117 issue at some extent this also encapsulate in a `ParseResult` the parsing data/metadata of a URL. Each URL has only one `ParseResult` which at the same time has at least 1 `ParseData` instance to hold the data of the "parent" URL in case subdocuments are extracted in any `ParseFilter` the URLs and ParseData of each subdocument is added to the parent ParseResult. So the `ParserBolt` emits each `ParseData` container in the `ParseResult` as a tuple. So at the very least 1 `ParseData`, or any number if subdocuments are extracted, also this implies that there is no difference between the extracted information about the parent URL or any subdocument each `ParseData` gets emitted as a tuple.
I made some simple graph to …
> Allowing the parse output to output more than one document

- core/crawler-conf.yaml
- core/src/main/java/com/digitalpebble/storm/crawler/bolt/SiteMapParserBolt.java
- core/src/test/java/com/digitalpebble/storm/crawler/bolt/SiteMapParserBoltTest.java
* added option to sniff content when triggering K/V is missing
* let the underlying sitemapparser guess the mimetype when it is not available
> Improvement to SitemapParserBolt

- external/solr/external-conf.yaml
- external/solr/pom.xml
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/SolrConnection.java
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/SolrCrawlTopology.java
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/bolt/IndexerBolt.java
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/metrics/MetricsConsumer.java
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/persistence/SolrSpout.java
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/persistence/StatusUpdaterBolt.java
Solr resources for StormCrawler, this add support for:
* IndexerBolt
* MetricsConsumer
* SolrSpout/StatusUpdaterBolt
* SolrConnection
* SolrCrawlTopology
The `SolrConnection` class have support for both the SolrCloud and a single Solr server by the ConcurrentUpdateSolrClient (CUSC). For using SolrCloud a `solr.TYPE.zkhost` needs to be specified instead of the `solr.TYPE.url`, also an additional parameter `solr.TYPE.collection` needs to be provided for the SolrCloud. I've detected a bug in the solr-solrj library regarding the use of the collection parameter in some methods (https://issues.apache.org/jira/browse/SOLR-7729), once this is fixed should simplify the code for the CUSC case, for now I recommend using the `url` parameter for the CUSC case to point directly to the solr collection …
> Adding support for [SOLR] Write Spout, StatusUpdaterBolt and Indexer

- core/src/main/java/com/digitalpebble/storm/crawler/parse/filter/ContentFilter.java
- core/src/main/resources/parsefilters.json
Partly implements #146
This is a very simple initial version which takes a number of XPath expressions and rewrite the text content of the document based on the text covered by the first Xpath expression which matches.
We can refine it later so that the expressions are applied based on a URL pattern or key value pair in the metadata.
> ContentFilter to restrict text of document to XPath match

- core/src/main/java/com/digitalpebble/storm/crawler/bolt/JSoupParserBolt.java
- core/src/main/java/com/digitalpebble/storm/crawler/indexing/AbstractIndexerBolt.java
- core/src/main/java/com/digitalpebble/storm/crawler/util/RobotsTags.java
- core/src/test/java/com/digitalpebble/storm/crawler/bolt/JSoupParserBoltTest.java
- core/src/test/java/com/digitalpebble/storm/crawler/parse/filter/ParsingTester.java
- core/src/test/java/com/digitalpebble/storm/crawler/util/RobotsTagsTest.java
- core/src/test/resources/digitalpebble.com.html
Implements #147 
* Added RobotsTags to represent the instructions provided in the HTTP headers or META tags.
* JSoupParserBolt bypasses the extraction of outlinks and AbstractIndexerBolt filters out document according to these values.
* JSoupParserBolt filters out links with `rel="nofollow"`
* Added RobotsTagsTest and JSoupParserBoltTest.
Will add the same behaviour to the Tika parser after merging #145 
> Enforce robots meta instructions

- core/src/main/java/com/digitalpebble/storm/crawler/indexing/AbstractIndexerBolt.java
- core/src/test/java/com/digitalpebble/storm/crawler/indexer/BasicIndexingTest.java
- core/src/test/java/com/digitalpebble/storm/crawler/indexer/DummyIndexer.java
- core/src/test/java/com/digitalpebble/storm/crawler/indexer/IndexerTester.java
- external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/bolt/IndexerBolt.java
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/bolt/IndexerBolt.java
This address the https://github.com/DigitalPebble/storm-crawler/issues/149 issue which provides a method in the `AbstractIndexerBolt` that returns the right URL to be indexed. In this case if a canonical URL is found its used instead of the original URL. Some sanity checks are done:
* The URL is resolved to avoid relative URLs
* The host of the canonical URL is compared with the host of the original URL and only used if is the same.
I've also updated the `StdOutIndexer` and the `IndexerBolt` of both Solr and Elasticsearch.
I wanted to test the logic in the new method so I've added a basic testing framework very similar to `com.digitalpebble.storm.crawler.parse` to easy the task. I've also created a `DummyIndexer` that is used to test the output, since the IndexerBolts are the end of the …
> Adding support for using the canonical URL in the IndexerBolts

- core/src/main/java/com/digitalpebble/storm/crawler/bolt/JSoupParserBolt.java
- external/solr/README.md
- external/solr/pom.xml
- external/solr/solr-conf.yaml
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/metrics/MetricsConsumer.java
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/persistence/SolrSpout.java
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/persistence/StatusUpdaterBolt.java
- external/tika/pom.xml
- pom.xml
A couple of parameters were added to handle diversity Issue #156: 
* `solr.status.diversity.field.name`: Indicates the name of the field to be collapsed on.
* `solr.status.diversity.field.bucket`: Indicates the maximum bucket size of each expanded group. 
One good example to add to the wiki/documentation around this is to use the `status` field, which can have a small set of values, so it will be easy to explain and is a field that is populated by default, and provide a good balance between each type of URLs. 
I'm going to make other commit adding some explanation to the README file in the Solr module, if thats ok.
A better param name is welcome :smile: 
Also this PR fix a small typo in a parameter configuration of the `MetricsConsumer` class.
> Adding support for field collapsing in the Solr Spout

- core/src/main/java/com/digitalpebble/storm/crawler/util/MetadataTransfer.java
Reverts DigitalPebble/storm-crawler#169
Better to know that a Metadata is null than silently ignore it
> Revert "Correction of a NPE in metadata transfert function"

- core/src/main/java/com/digitalpebble/storm/crawler/ConfigurableTopology.java
- core/src/main/java/com/digitalpebble/storm/crawler/protocol/httpclient/HttpProtocol.java
- core/src/main/java/com/digitalpebble/storm/crawler/util/ConfUtils.java
- core/src/main/java/com/digitalpebble/storm/crawler/util/MetadataTransfer.java
At the end of ConfUtils.loadConf(), you either have a (Config + yaml options) Map or a Config Map. Either way, there is no need for a second putAll().
> loadConf() already calls putAll()

- external/aws/README.md
- external/aws/aws-conf.yaml
- external/aws/pom.xml
- external/aws/src/main/java/com/digitalpebble/stormcrawler/aws/bolt/CloudSearchConstants.java
- external/aws/src/main/java/com/digitalpebble/stormcrawler/aws/bolt/CloudSearchIndexerBolt.java
- external/aws/src/main/java/com/digitalpebble/stormcrawler/aws/bolt/CloudSearchUtils.java
- pom.xml
This adds a new directory `aws` to the external resources. It contains an indexer bolt for AWS CloudSearch, more resources (e.g. SQS) might be added to it in the future.
See README for details and instructions of use.
> Resources for AWS CloudSearch

- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/persistence/SolrSpout.java
Merge the main result set with the expanded result set when a diversity field is used.
Use the size of the main results section for pagination
> Fixing issue with unique URL per host causing the Solr spout to lockup 

- core/src/main/java/com/digitalpebble/storm/crawler/filtering/robots/RobotsFilter.java
A simple URLFilter which discards URLs based on the robots.txt directives. This is meant to be used for small, vertical crawls where the number of hosts is limited. 
See discussion #24.
> Initial version of robots URL filter; see #24

- core/src/main/java/com/digitalpebble/storm/crawler/util/StringTabScheme.java
This is a fix for the issue #168
> Initialize the metadata in the StringTabScheme, should never be null

- external/solr/solr-conf.yaml
- external/solr/solr-example-cores/metrics/conf/solrconfig.xml
- external/solr/solr-example-cores/parse/conf/solrconfig.xml
- external/solr/solr-example-cores/status/conf/solrconfig.xml
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/SolrConnection.java
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/bolt/IndexerBolt.java
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/metrics/MetricsConsumer.java
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/persistence/StatusUpdaterBolt.java
This is a fix proposal for the issue #177.
- No explicits commit in the code
- Add autoCommit and autoSoftCommit in solrconfig files
- Update Lucene version in solrconfig files
> [External][Solr] The Solr storage should use 'autoSoftCommit' and 'autoCommit'

- core/src/main/java/com/digitalpebble/storm/crawler/bolt/SimpleFetcherBolt.java
This PR adds an internal throttler to SimpleFetcherBolt so that it can enforce politeness. This assumes that the tuples are directed to the SimpleFetcherBolt instances based on a their host, domain or IP. The configuration is similar to the FetcherBolt, the only difference in behaviour being that instead of skipping a URL if its robots specifies to high a value, we simply use the max delay configured.
> Throttler added to SimpleFetcherBolt 

- core/pom.xml
Updated the dependencies section to include snakeyaml and commons-lang as dependencies. Otherwise, the storm program and topology throw CNFEs.
> Include missing JAR dependencies in pom.xml

- core/pom.xml
Was 1.1.6 which looks like a typo. This is a build failure since it can't be found in maven repo.
> Fixed snakeyaml version

- external/elasticsearch/es-conf.yaml
- external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/ElasticSearchSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/StatusUpdaterBolt.java
This PR leverages the sharding functionalities of Elasticsearch to group URLs into shards per domain/host/IP. This is done so that one instance of the ES spouts can be used per shard and hence guarantee a good diversity of URLs into the topology and optimise the performance of the crawl.
When setting `es.status.routing` to true the StatusUpdater will generate a partition key for a URL (based on the value of 'partition.url.mode') to send a document to a specific shard.  Optionally the value used for sharding can be stored in the metadata under the field name specified in 'es.status.routing.fieldname'.
In order for the sharding to be used by the ES spouts, there must be as many instances created as there are shards in the index as each instance becomes responsible of a given shard.
The …
> ES Sharding

- external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/AggregationSpout.java
The `bucketSortField` variable was initialised with the default of `nextFetchDate` but then later overwritten.
Unlikely to be a problem since the default is also in the conf file.
> Use default of "nextFetchDate" for bucket sorting

- external/elasticsearch/es-conf.yaml
- external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/AggregationSpout.java
See #233
Currently implemented as a separate implementation from the existing one.
> AggregationSpout for field collapsing on ES. Implements #233

- core/src/main/java/com/digitalpebble/storm/crawler/ConfigurableTopology.java
- core/src/main/java/com/digitalpebble/storm/crawler/Metadata.java
- core/src/main/java/com/digitalpebble/storm/crawler/bolt/FetcherBolt.java
- core/src/main/java/com/digitalpebble/storm/crawler/bolt/JSoupParserBolt.java
- core/src/main/java/com/digitalpebble/storm/crawler/bolt/SiteMapParserBolt.java
- core/src/main/java/com/digitalpebble/storm/crawler/filtering/URLFilters.java
- core/src/main/java/com/digitalpebble/storm/crawler/filtering/basic/BasicURLNormalizer.java
- core/src/main/java/com/digitalpebble/storm/crawler/filtering/regex/RegexURLFilterBase.java
- core/src/main/java/com/digitalpebble/storm/crawler/filtering/regex/RegexURLNormalizer.java
- core/src/main/java/com/digitalpebble/storm/crawler/indexing/AbstractIndexerBolt.java
- core/src/main/java/com/digitalpebble/storm/crawler/parse/ParseFilters.java
- core/src/main/java/com/digitalpebble/storm/crawler/parse/filter/ContentFilter.java
- core/src/main/java/com/digitalpebble/storm/crawler/parse/filter/XPathFilter.java
- core/src/main/java/com/digitalpebble/storm/crawler/protocol/ProtocolFactory.java
- core/src/main/java/com/digitalpebble/storm/crawler/protocol/RobotRulesParser.java
- core/src/main/java/com/digitalpebble/storm/crawler/spout/FileSpout.java
- core/src/main/java/com/digitalpebble/storm/crawler/spout/MemorySpout.java
- core/src/main/java/com/digitalpebble/storm/crawler/util/MetadataTransfer.java
- core/src/test/java/com/digitalpebble/storm/crawler/filtering/BasicURLNormalizerTest.java
- core/src/test/java/com/digitalpebble/storm/crawler/filtering/HostURLFilterTest.java
- core/src/test/java/com/digitalpebble/storm/crawler/util/MetadataTransferTest.java
- external/aws/src/main/java/com/digitalpebble/stormcrawler/aws/bolt/CloudSearchIndexerBolt.java
- external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/AggregationSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/ElasticSearchSpout.java
- external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/persistence/SolrSpout.java
- external/sql/src/main/java/com/digitalpebble/storm/crawler/sql/SQLSpout.java
- external/tika/src/main/java/com/digitalpebble/storm/crawler/tika/DOMBuilder.java
- external/tika/src/main/java/com/digitalpebble/storm/crawler/tika/ParserBolt.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2293 - “ The diamond operator ("<>") should be used ”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S2293
> Simplify the generics declaration by using the diamond operator ("<>"……) to reduce the verbosity of generics code.

- core/src/main/java/com/digitalpebble/storm/crawler/bolt/SiteMapParserBolt.java
- core/src/main/java/com/digitalpebble/storm/crawler/bolt/URLPartitionerBolt.java
- core/src/main/java/com/digitalpebble/storm/crawler/filtering/URLFilters.java
- core/src/main/java/com/digitalpebble/storm/crawler/parse/JSoupDOMBuilder.java
- core/src/main/java/com/digitalpebble/storm/crawler/parse/ParseFilters.java
- core/src/main/java/com/digitalpebble/storm/crawler/protocol/httpclient/HttpProtocol.java
- core/src/main/java/com/digitalpebble/storm/crawler/util/PerSecondReducer.java
- core/src/main/java/com/digitalpebble/storm/crawler/util/URLPartitioner.java
- external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/AggregationSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/ElasticSearchSpout.java
- external/tika/src/main/java/com/digitalpebble/storm/crawler/tika/ParserBolt.java
This pull request is focused on resolving occurrences of Sonar rule squid:UselessParenthesesCheck - “ Useless parentheses around expressions should be removed to prevent any misunderstanding ”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
> Useless parentheses around expressions should be removed to prevent any misunderstanding

- core/src/main/java/com/digitalpebble/storm/crawler/Constants.java
- core/src/main/java/com/digitalpebble/storm/crawler/util/ConfUtils.java
- core/src/main/java/com/digitalpebble/storm/crawler/util/URLUtil.java
- core/src/test/java/com/digitalpebble/storm/crawler/TestUtil.java
- external/aws/src/main/java/com/digitalpebble/stormcrawler/aws/bolt/CloudSearchUtils.java
- external/sql/src/main/java/com/digitalpebble/storm/crawler/sql/Constants.java
- external/sql/src/main/java/com/digitalpebble/storm/crawler/sql/SQLUtil.java
- external/tika/src/main/java/com/digitalpebble/storm/crawler/tika/XMLCharacterRecognizer.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - “ Utility classes should not have public constructors ”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1118
> Adding private constructor to util classes (containing  static methods only)

- external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/AggregationSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/ElasticSearchSpout.java
The ES clients are thread-safe, there is no reason why they should not be shared among the Spout instances within the same worker. 
@mattburns what do you think?
> ES-based Spouts use a static Client instance

- core/src/main/java/com/digitalpebble/storm/crawler/filtering/basic/BasicURLNormalizer.java
- core/src/main/resources/urlfilters.json
The http protocol implementation is based on httpclient and requires the URLs to be well formed URIs. Work is needed to normalise them  see #205 but what we can do here is to filter them out - no point trying to fetch them
> Added option to BasicURLNormalizer for checking that a URL is a valid URI

- external/elasticsearch/es-conf.yaml
- external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/ElasticSearchConnection.java
Implements #259. Allows to specify a custom port and not just the hosts as well as multiple addresses for the TransportClient.
Note \: this change the config name from *.hostname to *.addresses and is not backward compatible.
> ES config to accept multiple addresses at host:port format #259

- core/pom.xml
- core/src/main/java/com/digitalpebble/storm/crawler/bolt/FetcherBolt.java
- core/src/main/java/com/digitalpebble/storm/crawler/bolt/SimpleFetcherBolt.java
- core/src/main/java/com/digitalpebble/storm/crawler/protocol/httpclient/HttpProtocol.java
- core/src/test/java/com/digitalpebble/storm/crawler/bolt/AbstractFetcherBoltTest.java
- core/src/test/java/com/digitalpebble/storm/crawler/bolt/SimpleFetcherBoltTest.java
see #279 
SimpleFetcherBolt does not emit to default stream when code 304. Added test using Wiremock + http protocol returns empty array when entity is null
The test cannot be used for FetcherBolt yet as the tuples get flushed to the collector based on ticktuples - this will be fixed with #278
> SimpleFetcherBolt handles 304 correctly

- archetype/src/main/resources/archetype-resources/crawler-conf.yaml
- core/src/main/java/com/digitalpebble/storm/crawler/util/MetadataTransfer.java
- core/src/main/resources/crawler-default.yaml
See #282 
This fixes a bug where metadata were passed to the outlinks unnecessarily and allows to distinguish between the md that are transferred to the outlinks and the ones that need persisting only for the current document.
This patch does not modify the behaviour of any preexisting configuration however users should update their configuration to make use of the new feature.
> Md persist only

- archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
- archetype/src/main/resources/archetype-resources/README.md
- archetype/src/main/resources/archetype-resources/crawler-conf.yaml
- archetype/src/main/resources/archetype-resources/crawler.flux
- archetype/src/main/resources/archetype-resources/pom.xml
- core/src/main/java/com/digitalpebble/storm/crawler/ConfigurableTopology.java
- core/src/main/java/com/digitalpebble/storm/crawler/util/ConfUtils.java
- core/src/main/resources/crawler-default.yaml
The crawl is defined in a file `crawler.flux` and the topology can get started with 
``` sh
storm jar target/<INSERTJARNAMEHERE>.jar  org.apache.storm.flux.Flux --local crawler.flux
```
The configuration (both custom and default) are now put in a root _config_ element so that the files can be used by both the ConfigurableTopology and Flux. The old format still works for the ConfigurableTopology.
> Add Flux equivalent of the example topology class #286

- external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/AggregationSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/storm/crawler/elasticsearch/persistence/SamplerAggregationSpout.java
See #299 
This introduces a new SamplerAggregationSpout which uses the Sampler aggregation from ES 2.x
Unlike the existing AggregationSpout there is no guarantee that the URLs returned will be the oldest available. This spout greatly reduces the average query time (by up to 50% in some cases) which improves the overall performance of the crawler. 
This new class extends AggregationSpout.
> ES SamplerAggregationSpout

- pom.xml
Some other Maven Modules depend on the new Jackson Databind.
All tests have passed.
> Update Jackson Databind Version to newer version

- core/src/main/java/com/digitalpebble/stormcrawler/util/MetadataTransfer.java
- external/elasticsearch/es-conf.yaml
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AbstractSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AggregationSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/ElasticSearchSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/SamplerAggregationSpout.java
Fixes #340 
The abstract class contains an extension of Map for the URLs in process, this extension also contains a Guava cache which gets populated when entries are removed from the map.
The time during which the entries remain in the cache is configurable. We also report 2 separate metrics for the # of entries in the map and in the cache.
Not yet tested but reviews welcome as usual
FYI @sebastian-nagel
> ES Cache URLs post ack/fail

- archetype/src/main/resources/archetype-resources/crawler-conf.yaml
- archetype/src/main/resources/archetype-resources/src/main/resources/parsefilters.json
- core/src/main/java/com/digitalpebble/stormcrawler/parse/filter/DomainParseFilter.java
Used by archetype to generate a field 'domain' when indexing. The name of the metadata key can be changed via config + can also select to use the hostname instead.
> DomainParseFilter

- external/elasticsearch/es-conf.yaml
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AbstractSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AggregationSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/ElasticSearchSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/SamplerAggregationSpout.java
- don't sleep for the whole delay as this would block ack/fails
> Use min.delay.queries for all types of spouts 

- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AbstractSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AggregationSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/ElasticSearchSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/SamplerAggregationSpout.java
Implements #371 and fixes a bug introduced in #370 
Not implemented in the non-aggregation spout for now.
This should improve the performance a bit as slow queries to ES should not block ack and fail.
> Non-blocking calls to ES for AggregationSpouts

- core/src/main/java/com/digitalpebble/stormcrawler/parse/filter/MD5SignatureParseFilter.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/AbstractStatusUpdaterBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/AdaptiveScheduler.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/DefaultScheduler.java
Add implementation of Scheduler which 
- checks fetch status (304 not modified) or compares previous and current signature
to decide whether a page has changed since the previous fetch
- if changed, decreases the fetch interval
- otherwise increases it up to a configurable limit
See also commoncrawl/news-crawl#15.
Possible TODOs:
- add unit tests
- simplify configuration
- interaction with parse filters to provide signatures (old and new)
- reduce amount of persisted metadata (need metadata to be kept in the topology but not necessarily persisted in storage)
> Add adaptive fetch scheduler

- core/src/main/java/com/digitalpebble/stormcrawler/bolt/FetcherBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/AdaptiveScheduler.java
fixes #418:
- overwrite persisted fetch.statusCode in FetcherBolt
- ignore persisted signatures in AdaptiveScheduler in case of HTTP 304
> Adaptive schedule HTTP 304 ignore persisted signatures

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java
- core/src/main/resources/crawler-default.yaml
Modified HttpProtocol to optionally accept a proxy username, password and auth scheme. It currently only supports basic authentication because that's the only one I can test against.
Additional configuration parameters to leverage this functionality are:
```
http.proxy.user: [proxy username, if not present authentication is not used]
http.proxy.pass: [proxy password, if not present authentication is not used]
```
Also removed a throws Exception because it never throws that exception, and cleaned up the builder usage code.
> HTTP Proxy over Basic Authentication

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/AbstractHttpProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/util/CookieConverter.java
- core/src/test/java/com/digitalpebble/stormcrawler/util/CookieConverterTest.java
OK , trying again, with all requested adjustments.
> Resolve issue #32 - implement cookie handeling

- core/pom.xml
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/selenium/NavigationFilter.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/selenium/NavigationFilters.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/selenium/RemoteDriverProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/selenium/SeleniumProtocol.java
This PR contains much of the code from the jBrowserDriver branch and implements #144. Instead to being tied to a particular library, it provides a neutral RemoteDriverProtocol which can be configured to connect to one or more endpoints.
The code in JBrowserDriver could be refactored later on to be based on this.
There is a lot more work to do on this e.g. pass configuration, setup timeouts etc... but at least this would be a good starting point.
To run with phantomjs on Linux
```
sudo apt install phantomjs
phantomjs --webdriver 9515
```
then set in the config\:
`selenium.addresses: "http://localhost:9515"`
> Abstract Selenium protocol, NavigationFilters and RemoteDriverProtocol

- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AbstractSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AggregationSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/CollapsingSpout.java
implements #452 for the AggregationSpout
Introduces 2 new parameters which set the nextFetchDate to query on based on the most recent date returned by the latest query. A duration in minutes is added to this date and will be used for querying unless the previous date was within N minutes of the new one. This way we can hit the caches.
> Optimise nextFetchDate to speed up queries to Elasticsearch

- core/src/main/java/com/digitalpebble/stormcrawler/bolt/JSoupParserBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/util/CharsetIdentification.java
Implements #438 
The detection code is now separate from JSoup and has a better strategy: we detect the charset based on
1. the Byte Order Mark if any
2. the HTTP header and HTML meta if they concur
3. a third party library using a hint or not
> Charset Detection

- core/src/main/java/com/digitalpebble/stormcrawler/parse/filter/LDJsonParseFilter.java
- core/src/test/java/com/digitalpebble/stormcrawler/parse/filter/XPathFilterTest.java
- core/src/test/resources/digitalpebble.com.html
- core/src/test/resources/test.parsefilters.json
ParseFilter implementation to extract data from [json-ld](https://json-ld.org/) representations, typically used with schema.org
Takes as parameter a number of mappings metadata name => JsonPointer expression
```
{
"class": "com.digitalpebble.stormcrawler.parse.filter.LDJsonParseFilter",
"name": "LDJsonParseFilter",
"params": {
"streetAddress": "/location/streetAddress"
}
}
```
> LDJsonParseFilter

- external/warc/pom.xml
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/FileTimeSizeRotationPolicy.java
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/GzipHdfsBolt.java
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCHdfsBolt.java
Tested so far in small scale:
- WARC files validate
- file rotation by size works
A large scale test will follow during the next days.
A first trial to implement a class GzipHdfsWriter extending AbstractHDFSWriter (AbstractHDFSWriter needs to be returned by `AbstractHdfsBolt.makeNewWriter(path, tuple)`) wasn't successful:
- the field `offset` in AbstractHDFSWriter is only visible in the package `org.apache.storm.hdfs.common`, it cannot be used in a Storm-crawler package
-  the method `write(tuple)` which accesses the package-internal `offset` is final:
```
abstract public class AbstractHDFSWriter {
long offset;
final public long write(Tuple tuple) throws IOException{
doWrite(tuple);
this.needsRotation = rotationPolicy.mark(tuple, offset);
return this.offset;
}
}
```
I didn't find a way to …
> Upgrade WARC module to latest version of storm-hdfs, fixes #590

- core/src/main/java/com/digitalpebble/stormcrawler/filtering/basic/BasicURLNormalizer.java
- core/src/test/java/com/digitalpebble/stormcrawler/filtering/BasicURLNormalizerTest.java
- conversion of IDN host names to their ASCII/Punycode equivalent is triggered if param "hostIDNtoASCII" is true
- avoids duplicate page content
- get clean ASCII keys if sharding/routing is done by host or domain
> BasicURLNormalizer to optionally convert IDN host names to ASCII/Punycode

- archetype/src/main/resources/archetype-resources/crawler-conf.yaml
- core/src/main/resources/crawler-default.yaml
Based on the discussion here https://github.com/DigitalPebble/storm-crawler/issues/533
We are setting the default  `http.content.limit` to `-1` in the default config, whereas in the archetype to `65536`, a more clear approach for the user.
> http.content.limit inconsistent default to -1 #533

- core/src/main/java/com/digitalpebble/stormcrawler/filtering/basic/BasicURLNormalizer.java
- core/src/main/java/com/digitalpebble/stormcrawler/spout/FileSpout.java
and improve logging of IDN URLs which fail to be converted to ASCII/Punycode
If the system local / default encoding is not UTF-8, non-ASCII seeds may fail to get injected. I've seen this while testing in a Docker container: the seed `https://арктик-тв.рф/rss/arctic-tv.xml` caused the error:
```
2018-03-06 11:09:11.273 c.d.s.f.URLFilters Thread-14-filter-executor[5 5] [ERROR] URL filtering threw exception
java.lang.IllegalArgumentException: java.text.ParseException: A prohibited code point was found in the input????????????-????
at java.net.IDN.toASCIIInternal(IDN.java:274) ~[?:1.8.0_151]
at java.net.IDN.toASCII(IDN.java:122) ~[?:1.8.0_151]
at java.net.IDN.toASCII(IDN.java:151) ~[?:1.8.0_151]
at com.digitalpebble.stormcrawler.filtering.basic.BasicURLNormalizer.filter(BasicURLNormalizer.java …
```
> Use UTF-8 for input encoding of seeds (FileSpout)

- archetype/src/main/resources/archetype-resources/src/main/resources/default-regex-filters.txt
To avoid that information is leaked and exposed in a public search interface, a web crawler should never follow links to localhost, loop-back addresses and private address spaces, see commoncrawl/news-crawl#21. These are excluded by regular expressions for http/https URLs.
Of course, could comment out the rules to enable test crawls of the local Apache web server.
> Default URL filter: exclude localhost and private address spaces

- core/src/main/java/com/digitalpebble/stormcrawler/bolt/FetcherBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/bolt/SimpleFetcherBolt.java
- core/src/main/resources/crawler-default.yaml
to guarantee that the crawler always behaves polite and inconspicuous, see commoncrawl/news-crawl#24.
> Crawl-delay in robots.txt should not shrink delay configured by fetcher.server.delay

- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/StatusUpdaterBolt.java
Hi Julien,
this PR prints errors, if we get some in the callback from elastic search.
It happened to me that the ES index switched to read-only and I wondered why nothing gets updated, since there is no failure indication.
Cheers,
Jens
> status update: log error if elastic search reports an unexpected problem

- core/src/main/java/com/digitalpebble/stormcrawler/filtering/regex/FastURLFilter.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java
Hello,
This is a simple basic auth system that allow user to add these parameters into the yaml configuration :
-   http.basicauth.enabled: true
-   http.basicauth.user: "root"
-   http.basicauth.password: "root"
This way it allows stormcrawler to be used in most of the intranets.
If this PR is accepted I'll produce the documentation associated.
Thanks
> Add simple basic auth system

- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/bolt/DeletionBolt.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/bolt/IndexerBolt.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/StatusUpdaterBolt.java
Added `getIndexName(Metadata m)` method in bolts responsible for interacting with ES indexes. This allow implementing custom indexes names based on some metadata information.
> Added ability to implement custom indexes names based on metadata information, fixes #591

- core/src/main/java/com/digitalpebble/stormcrawler/filtering/URLFilter.java
- core/src/main/java/com/digitalpebble/stormcrawler/filtering/URLFilters.java
- core/src/main/java/com/digitalpebble/stormcrawler/parse/ParseFilter.java
- core/src/main/java/com/digitalpebble/stormcrawler/parse/ParseFilters.java
- core/src/main/java/com/digitalpebble/stormcrawler/util/Configurable.java
This PR introduces a new interface Configurable which is implemented by both ParseFilter and URLFilter. It also contains code for the wrapper classes  URLFilters and ParseFilters so that they share the loading of resources from JSON files. These classes also implement JSONResource.
> URLFilters + ParseFilters refactoring

- core/src/main/java/com/digitalpebble/stormcrawler/bolt/FetcherBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/bolt/SimpleFetcherBolt.java
FetcherBolt already read the byteLength from the response, but didn't add it to Metadata.
(This could be helpful if you want to index the document size)
> Added byteLength to Metadata

- external/sql/src/main/java/com/digitalpebble/stormcrawler/sql/Constants.java
- external/sql/src/main/java/com/digitalpebble/stormcrawler/sql/SQLUtil.java
- external/sql/src/main/java/com/digitalpebble/stormcrawler/sql/StatusUpdaterBolt.java
This PR changes the behaviour of the SQL StatusUpdaterBolt by batching the INSERTs, i.e. the discovered URLs which are far more frequent than updates.
@cruftex plz let me know what you think. we can make it SQL agnostic in a separate step.
> Batch PreparedStatements in SQL status updater bolt, fixes #610

- core/src/main/java/com/digitalpebble/stormcrawler/persistence/AbstractQueryingSpout.java
- external/elasticsearch/es-conf.yaml
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AbstractSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AggregationSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/CollapsingSpout.java
- external/solr/solr-conf.yaml
- external/solr/src/main/java/com/digitalpebble/stormcrawler/solr/persistence/SolrSpout.java
- external/sql/sql-conf.yaml
- external/sql/src/main/java/com/digitalpebble/stormcrawler/sql/Constants.java
- external/sql/src/main/java/com/digitalpebble/stormcrawler/sql/SQLSpout.java
implements #617
Refactoring of spout implementations. The ones in the external modules have in common that they generate tuples based on queries to a backend (e.g. SOLR, SQL, ES).  The introduction of the class AbstractQueryingSpout simplifies the implementations of these spouts by taking care of the query throttling, caching of URLs in process, instantiation of the metrics etc...
Some of the configuration names have been deprecated as a result.
> Abstract functionalities of spout implementations

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
In this version, the `HttpProtocol` classes have been updated to optionally use `Accept` and `Accept-Language` header values obtained from the `Metadata` object over the globally configured defaults.
This satisfies Feature Request #629
> Override Globally Configured Accepts and Accepts-Language Headers Per-URL

- core/src/main/java/com/digitalpebble/stormcrawler/bolt/SiteMapParserBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/DefaultScheduler.java
- core/src/main/resources/crawler-default.yaml
Fixed #657
adds a mechanism to the default scheduler for adding a delay based on a value specified in the metadata. Applied prior to the rules set in config
>  Staggered scheduling of sitemap URLs

- core/src/main/java/com/digitalpebble/stormcrawler/bolt/JSoupParserBolt.java
- core/src/main/resources/crawler-default.yaml
- core/src/test/java/com/digitalpebble/stormcrawler/bolt/JSoupParserBoltTest.java
Added a new property called `parser.emitOutlinks.max.per.page` in config file, to be used for limiting quantity of outlinks discovered in a page during parsing.
If `parser.emitOutlinks.max.per.page : -1` limit will be disabled. Default value of this property is -1.  
Change is really straight forward .
Thanks 
Juan
> 669: Implement outlink limit per page

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/HttpHeaders.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
Format the last-modified ISO date persisted in metadata as HTTP-Date when sending If-Modified-Since requests. Fixes #673.
> Date format used for HTTP if-modified-since requests must follow RFC 7231

- archetype/src/main/resources/archetype-resources/crawler-conf.yaml
- archetype/src/main/resources/archetype-resources/src/main/resources/parsefilters.json
- core/src/main/java/com/digitalpebble/stormcrawler/bolt/JSoupParserBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/parse/TextExtractor.java
- core/src/main/java/com/digitalpebble/stormcrawler/parse/filter/ContentFilter.java
- core/src/test/java/com/digitalpebble/stormcrawler/parse/TextExtractorTest.java
Fixes #638 and #150 
Provides better text extraction than the ContentFilter, which agglutinated tokens found within a restricted section, plus allows to exclude portions of text.
The TextExtractor class is used within JSoupParserBolt only.
The archetype has been modified so that the ContentFilter is replaced by the TextExtractor with a similar configuration.
> Added configurable TextExtractor to JSoupParserBolt

- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/ElasticSearchConnection.java
In this version it is possible to optionally configure overrides for elasticsearch's default RestClient timeouts.
Options are:
```
es.[BOLT TYPE].connect.timeout: // Timeout for establishing a connection (if the value is 0, the timeout is considered "infinity")
es.[BOLT TYPE].socket.timeout: // Timeout for receiving data (if the value is 0, the timeout is considered "infinity")
es.[BOLT TYPE].max.retry.timeout: // The time before a connection retry is considered to have timed out (must be > 0)
```
All values should be in millis.
If no values are supplied, the elasticsearch defaults are used.
> Optional timeout configurations for elasticsearch's RestClient

- core/src/main/java/com/digitalpebble/stormcrawler/persistence/AbstractQueryingSpout.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/AbstractStatusUpdaterBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/DefaultScheduler.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/ScrollSpout.java
Implements  #688 and fixes #684
This adds a ScrollSpout for ES as well as a mechanism to the AbstractStatusUpdaterBolt so that it stores a tuple without modifying any of its content. 
The following Flux illustrates its use
```
name: "reindexer"
includes:
- resource: true
file: "/crawler-default.yaml"
override: false
- resource: false
file: "crawler-conf.yaml"
override: true
- resource: false
file: "es-conf.yaml"
override: true
config:
es.status2.addresses: "localhost"
es.status2.index.name: "status2"
es.status2.doc.type: "status"
es.status2.routing: true
es.status2.routing.fieldname: "key"
es.status2.bulkActions: 500
es.status2.flushInterval: "1s"
es.status2.concurrentRequests: 5
es.status2.settings:
cluster.name: "elasticsearch"
topology.max.spout.pending: 5000
topology.workers: 1 …
```
> Add a ScrollSpout to read all the documents from a shard

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/ProtocolResponse.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
- core/src/main/resources/crawler-default.yaml
- external/warc/README.md
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/GzipHdfsBolt.java
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCHdfsBolt.java
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCRecordFormat.java
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCRequestRecordFormat.java
- external/warc/src/test/java/com/digitalpebble/stormcrawler/warc/WARCRecordFormatTest.java
This PR combines a list of improvements to the WARC writer bolt and record formats but also to the okhttp-based protocol implementation:
- generate WARC request records (#509) by calling `withRequestRecords()` on an existing WARCHdfsBolt.
- use capture time (when fetching began) for WARC-Date not the time the WARC record is written. This also ensures that response and request record have the same `WARC-Date`
- add field `WARC-IP-Address (address commoncrawl/news-crawl#29)
- ports back a couple of improvements from Nutch's protocol-okhttp:
- use okhttp's internal byte buffer, do not buffer content twice
- optionally keep partially fetched content (e.g., if a single read fails with a socket timeout) if `http.content.partial.as.trimmed` is true
- track reason for trimmed content (content or …
> WARC format improvements

- core/src/main/java/com/digitalpebble/stormcrawler/bolt/URLFilterBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/spout/FileSpout.java
- external/elasticsearch/es-injector.flux
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/ESSeedInjector.java
- ESSeedInjector: explicitly set name of stream for source of URL filter bolt
- more verbose logging in FileSpout and URLFilterBolt - for easier debugging to exclude trivial reasons such as URLs have been filtered due to misconfigured filters
- add optional URL filter bolt config to es-injector.flux
> ESSeedInjector: filter bolt to subscribe to spout's status stream, fixes #715

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/HttpRobotRulesParser.java
- cache redirected robots.txt for the target host only if the robots.txt is at the root (URL path = `/robots.txt`)
- always cache the rules of a redirection for the source host
First check the example from #573 where a redirected robots.txt must not be cached for the target host:
```
2019-05-03 12:42:50.707 c.d.s.p.RobotRulesParser FetcherThread #33 [DEBUG] Cache miss http:wyomingtheband.com:80 for http://wyomingtheband.com/
2019-05-03 12:42:50.957 c.d.s.p.RobotRulesParser FetcherThread #33 [DEBUG] Robots for http://wyomingtheband.com/ redirected to https://www.facebook.com/wyomingtheband/robots.txt (not cached for target host because not at root)
2019-05-03 12:42:51.352 c.d.s.p.RobotRulesParser FetcherThread #33 [DEBUG] Caching robots for http://wyomingtheband.com/ under key …
```
> Review Robots' caching logic, fixes #713

- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/GzipHdfsBolt.java
Check whether output stream is not null before flushing and closing.
> NPE in WARCHdfsBolt on cleanup(), fixes #720

- core/src/main/java/com/digitalpebble/stormcrawler/util/CookieConverter.java
The coockie parser test will fail on german pc bacause the SimpleDateFormatter will use german day names at the expire check in CookieConverter
> Force English Locale for SimpleDateFormat in coockie converter.

- core/src/main/java/com/digitalpebble/stormcrawler/bolt/FetcherBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/AbstractQueryingSpout.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/AbstractURLBuffer.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/EmptyQueueListener.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/SimpleURLBuffer.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/URLBuffer.java
- core/src/main/resources/crawler-default.yaml
- core/src/test/java/com/digitalpebble/stormcrawler/persistence/URLBufferTest.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/ElasticSearchConnection.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AbstractSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AggregationSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/CollapsingSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/HybridSpout.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/ScrollSpout.java
- external/solr/src/main/java/com/digitalpebble/stormcrawler/solr/persistence/SolrSpout.java
- external/sql/src/main/java/com/digitalpebble/stormcrawler/sql/SQLSpout.java
Most spouts currently hold a queue of tuples waiting to be released and a set of strings to check whether an incoming tuple is already being processed or not. This PR replaces them with a URLBuffer which combines both functionalities and offers a lower level synchronisation mechanism. This makes it easier to write test code and simplifies the logic of the spouts. The implementation is pluggable and it is possible to specify any class implementing the URLBuffer interface. The default implementation puts the URLs into buckets based on the hostname and returns the tuples by iterating on the buckets. Other implementations could optimise the buckets based on how fast its URLs get processed.
Additionally, this PR contains a first version of a hybrid spout for ES which extends AggregationSpout …
> Pluggable URLBuffer and hybrid Elasticsearch spout

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
(fixes #756)
With the patch applied the content is reliably marked as trimmed:
```
> java -cp ... com.digitalpebble.stormcrawler.protocol.okhttp.HttpProtocol ... http://localhost/sitemap.xml
...
http.trimmed.reason: length
...
http.trimmed: true
```
> okhttp protocol: reliably mark trimmed content because of content limit

- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/filtering/JSONURLFilterWrapper.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/parse/filter/JSONResourceWrapper.java
`JSONURLFilterWrapper` and `JSONResourceWrapper` will always throw a `NullPointerException` during their `Timer`'s run method as `JSONResource resource` is never initialized.
Also cleans up invalid calls to `LOG.error`.
> Fix NullPointerException in JSONResourceWrappers

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/RobotRulesParser.java
> Crawl-delay handling: allow `fetcher.max.crawl.delay` exceed 300 sec., fixes #768

- archetype/src/main/resources/archetype-resources/README.md
The Storm 2.x command-line parser has been rewritten. Without any additional hint it also consumes the options and flags for the crawl topology class. The `--` tells storm that the remaining options and flags should be passed to the topology main class. Storm options need be given before.
Without the `--` when launching the topology via `storm jar` or `storm local` the `-conf` options are stripped and the Java command is logged:
```
Running: java ... package.CrawlTopology /path/es-conf.yaml /path/crawler-conf.yaml
```
Consequently, the crawl topology does not read the configuration files. By calling the topology as
```
storm {jar,local} [<storm-opts>] -- package.CrawlTopology [<crawl-topology-opts>]
```
the Java command correct:
```
Running: java ... package.CrawlTopology -conf …
```
> (Storm 2.x) Fix call of storm jar / storm local in README

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
The verbatim HTTP request header saved in metadata by the okhttp protocol implementation does not contain the protocol name and version in the request message. The request message should be (instead of `GET /path `):
```
GET /path HTTP/1.1
```
See also commoncrawl/news-crawl#34.
This PR adds
- the HTTP protocol name and version to the request message
- normalizes the protocol name for HTTP/2 (okhttp's internal name is "H2")
Two notes:
- HTTP/2 is enabled by default but requires Java 9 upwards, e.g. when running with OpenJDK 11 request/response headers are now:
```
$> /usr/lib/jvm/java-11-openjdk-amd64/bin/java ... com.digitalpebble.stormcrawler.protocol.okhttp.HttpProtocol \
-c ... https://www.google.com/
...
_request.headers_: GET / HTTP/2
...
_response.headers_: HTTP/2 200 
...
```
- …
> okhttp protocol: HTTP request header lacks protocol name and version

- core/src/main/java/com/digitalpebble/stormcrawler/Metadata.java
- core/src/main/java/com/digitalpebble/stormcrawler/bolt/FeedParserBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/bolt/FetcherBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/bolt/JSoupParserBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/bolt/SimpleFetcherBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/AbstractHttpProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/ProtocolResponse.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
- core/src/main/resources/crawler-default.yaml
- core/src/test/java/com/digitalpebble/stormcrawler/bolt/FeedParserBoltTest.java
- external/tika/src/main/java/com/digitalpebble/stormcrawler/tika/ParserBolt.java
- external/tika/src/test/java/com/digitalpebble/stormcrawler/tika/ParserBoltTest.java
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCHdfsBolt.java
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCRecordFormat.java
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCRequestRecordFormat.java
- external/warc/src/test/java/com/digitalpebble/stormcrawler/warc/WARCRecordFormatTest.java
fixes #776
@sebastian-nagel is that what you had in mind?
> Prefix protocol metadata 

- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/bolt/IndexerBolt.java
Elasticsearch Indexer bolt is acking before emit tuples in afterBulk method is causing ack failures in spout after timeout set in topology.
Order recommended by storm for correctly acking is emit and then ack
> Issue # 800 : elasticsearch IndexerBolt issue causing ack failures

- core/src/main/java/com/digitalpebble/stormcrawler/spout/FileSpout.java
- external/warc/README.md
- external/warc/pom.xml
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCRecordFormat.java
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCRequestRecordFormat.java
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCSpout.java
A simple WARC spout:
- inherits from FileSpout to read paths/URLs from local files
- based on [jwarc](//github.com/iipc/jwarc)
- mimics the behavior of FetcherBolt, i.e.
- all captures are sent to status stream
- only successful fetches (HTTP status 200) will emit content to default stream for parsing, indexing, etc.
Tested so far only with a few WARC files, both local and Common Crawl files referenced by URL `http://commoncrawl.s3.amazonaws.com/crawl-data/...`
> WARC spout to emit captures into topology (implements #755)

- core/src/main/java/com/digitalpebble/stormcrawler/persistence/AdaptiveScheduler.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
- core/src/test/java/com/digitalpebble/stormcrawler/persistence/AdaptiveSchedulerTest.java
- this PR assumes that the HTTP last-modified field is kept separately, see `protocol.md.prefix` and #776
- set `last-modified` in metadata
- for the initial successful fetch (also after error status)
- and if a change of the content signature indicates a modification
- clear `last-modified` for permanent failures (status ERROR)
- set `fetchInterval` in metadata for initial fetches scheduled by DefaultScheduler
> AdaptiveScheduler to set last-modified time in metadata, fixes #777

- core/src/main/java/com/digitalpebble/stormcrawler/bolt/SiteMapParserBolt.java
- core/src/main/resources/crawler-default.yaml
- core/src/test/java/com/digitalpebble/stormcrawler/bolt/SiteMapParserBoltTest.java
- core/src/test/resources/digitalpebble.sitemap.extensions.all.xml
- core/src/test/resources/digitalpebble.sitemap.extensions.image.xml
- core/src/test/resources/digitalpebble.sitemap.extensions.links.xml
- core/src/test/resources/digitalpebble.sitemap.extensions.mobile.xml
- core/src/test/resources/digitalpebble.sitemap.extensions.news.xml
- core/src/test/resources/digitalpebble.sitemap.extensions.video.xml
Implemented Sitemap extension parsing (issue #749)
- extracting the extension attributes out of each extension object for a given Sitemap URL added adding it to the outlink metadata object (prefixed by the extension type)
Somewhat related, while implementing this, I noticed that crawler-commons isn't adding the `duration` attribute from the `VideoExtension` to the map generated by `VideoExtension.asMap()` (oversight on my part).  I wrote this up as an issue, [crawler-commons/300](https://github.com/crawler-commons/crawler-commons/issues/300) and submitted a PR.  A future release will include duration, however, it will be missing from StormCrawler until a new version of `crawler-commons` is published with the fix.
> Implemented Sitemap extension parsing (issue #749)

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/HttpHeaders.java
- core/src/test/java/com/digitalpebble/stormcrawler/protocol/HttpHeadersTest.java
- provide ISO_INSTANT formatter with "UTC" time zone
- add unit test to verify date parsing and formatting as HTTP date used for the "If-modified-since" header (the dates to verify #820 are commented out)
... first part to fix #821, I'll try to find a solution for #820 as well and update the PR
> Fix HttpHeaders#formatDate to parse ISO dates, fixes #821

- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCSpout.java
Same as (Simple)FetcherBolt WARCSpout should add "fetch.statusCode" which holds HTTP status code to metadata. It's required by AdaptiveScheduler which will fail with a NPE if the field is not provided.
> WARCSpout: add metadata field "fetch.statusCode" (HTTP status code)

- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCSpout.java
Add the capture time from the WARC header to metadata field `_request.time_` same as done by the okhttp protocol. Of course, the capture time is useful when indexing the archive content, it's even required if WARC files are re-archived.
> WARCSpout to add `_request.time_` to metadata

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/AbstractHttpProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/util/ConfUtils.java
- core/src/main/resources/crawler-default.yaml
- external/warc/README.md
implements #827
- configuration key `http.protocol.versions` holds a list of protocols in order of preference
- implement selection of protocols in okhttp protocol implementation (httpclient should pick this once HTTP/2 is supported)
- fix loading of YAML lists when configuration isn't loaded via Storm (eg. by main method of AbstractHttpProtocol)
- add notice about protocol version to warc module README
> HTTP protocol implementation: allow to configure which protocol version(s) to use

- core/src/main/java/com/digitalpebble/stormcrawler/spout/FileSpout.java
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCSpout.java
fixes #825
- FileSpout: check for type of message ID
byte[] : replay
String : log error, cannot replay
(anything else) : log error and throw Exception
- WARCSpout: log error, cannot replay
> WARCSpout/FileSpout: ClassCastException if message ID of failed tuples is not of type byte[]

- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCSpout.java
Stupid bug: if `http.content.limit` is -1 (the default), WARCSpout shrinks its internal buffer size to the "lower" content limit size which causes an exception if it tries to allocate a ByteBuffer of negative size:
```
java.lang.IllegalArgumentException: null
at java.nio.ByteBuffer.allocate(ByteBuffer.java:334) ~[?:1.8.0_222]
at com.digitalpebble.stormcrawler.warc.WARCSpout.getContent(WARCSpout.java:248) ~[stormjar.jar:?]
at com.digitalpebble.stormcrawler.warc.WARCSpout.nextTuple(WARCSpout.java:479) ~[stormjar.jar:?]
```
> WARCSpout: IllegalArgumentException if http.content.limit == -1

- core/src/main/java/com/digitalpebble/stormcrawler/Constants.java
- external/warc/src/main/java/com/digitalpebble/stormcrawler/warc/WARCSpout.java
- if http.content.limit is -1 trim content to the max. possible array size
The following issues where fixes to allow testing with 3 WARC files holding content of [2^31-8 (safe)](https://github.com/DigitalPebble/storm-crawler/files/5880994/test-size-int-max-safe.warc.gz), [2^31-1 (int_max)](https://github.com/DigitalPebble/storm-crawler/files/5880999/test-size-int-max.warc.gz) and [2^31 bytes](https://github.com/DigitalPebble/storm-crawler/files/5881003/test-size-int-max-overflow.warc.gz) and to fix bugs detected while testing these edge cases:
- when reading into multiple buffers: do not read more bytes than necessary
- avoid an integer overflow when reporting length of truncation
- implement gzip and deflate Content-Type decompression
> WARCSpout doesn't handle http.content.limit -1 correctly, fixes #850

- core/src/main/java/com/digitalpebble/stormcrawler/persistence/AbstractStatusUpdaterBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/AdaptiveScheduler.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/DefaultScheduler.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/MemoryStatusUpdater.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/Scheduler.java
- core/src/main/java/com/digitalpebble/stormcrawler/persistence/StdOutStatusUpdater.java
- core/src/test/java/com/digitalpebble/stormcrawler/persistence/AdaptiveSchedulerTest.java
- core/src/test/java/com/digitalpebble/stormcrawler/persistence/DefaultSchedulerTest.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/StatusUpdaterBolt.java
- external/solr/src/main/java/com/digitalpebble/stormcrawler/solr/persistence/StatusUpdaterBolt.java
- external/sql/src/main/java/com/digitalpebble/stormcrawler/sql/StatusUpdaterBolt.java
implements #861
Using Optional<Date> would have worked but require a big change in the API whereas _null_ allows to keep it as it is.
@sebastian-nagel any thoughts?
> Scheduler implementations return an Optional<Date>

- core/src/main/java/com/digitalpebble/stormcrawler/util/CharsetIdentification.java
Fixed issue #892 
We have to ensure that were enough content for a recursive call with a bit large window.
If we have found broken the meta tag we should return null.
> Fixed bug with StackOverflowError in fast charset identification

- core/src/main/java/com/digitalpebble/stormcrawler/Metadata.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/DelegatorProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/selenium/DelegatorRemoteDriverProtocol.java
- core/src/test/java/com/digitalpebble/stormcrawler/protocol/DelegationProtocolTest.java
- core/src/test/resources/delegator-conf.yaml
See #899 
Adds a protocol implementation which delegates calls to sub protocol implementations based on matches on key / values in the metadata.
Gets configured via the standard config mechanism without requiring any additional files e.g.
```
protocol.delegator.config:
- className: "com.digitalpebble.stormcrawler.protocol.httpclient.HttpProtocol"
filters:
domain: "example.com"
depth: "3"
test: "true"
- className: "com.digitalpebble.stormcrawler.protocol.okhttp.HttpProtocol"
filters:
js: "true"
- className: "com.digitalpebble.stormcrawler.protocol.okhttp.HttpProtocol"
```
with each implementation being configured in the usual way. 
The matches are tried in the order listed, the last implementation specified must not have any filters as it is used as the default value.
A filter can have a …
> DelegatorProtocol

- external/elasticsearch/archetype/src/main/resources/archetype-resources/es-crawler.flux
Changed es-crawler.flux to connect status-metrics bolt to the __system component using the __tick stream. This will avoid sending the complete tuple that is not being used and fix ConcurrentModificationException for Metadata class.
```
Version 1.1 …
```
> ISSUE-909: ConcurrentModificationException for Metadata in StatusMetricsBolt

- core/pom.xml
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
enables OkHttp's interceptor to handle [Brotli](https://en.wikipedia.org/wiki/Brotli) Content-Encoding
> OkHttp protocol: add support for Brotli compression (Content-Encoding)

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
- send HEAD request if `http.method.head` is in page metadata and is true
- ports the behavior of #485 to the okhttp-based protocol implementation
- fix deprecation warning in POST method
> Support HEAD method in okhttp protocol

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/HttpRobotRulesParser.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
- core/src/main/resources/crawler-default.yaml
Add property `http.robots.content.limit` to configure the robots.txt content limit independent from `http.content.limit`
- fixes #921 "http.content.limit has effect on robots.txt"
- default is 512 kiB to follow the [robots.txt RFC draft](https://datatracker.ietf.org/doc/html/draft-rep-wg-topic-00#section-2.5)
> Allow to set http.content.limit per page in metadata

- core/src/main/java/com/digitalpebble/stormcrawler/parse/JSoupFilters.java
- core/src/main/java/com/digitalpebble/stormcrawler/parse/ParseFilters.java
Fixed issue #925 
Removed the static field into JSoupFilters. Also, removed the never used _configFile_ value into ParserFilters.
> Remove static keyword on JSoupFilters field

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
- core/src/main/resources/crawler-default.yaml
[OkHttp's ConnectionPool](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-connection-pool/) by default "holds up to 5 idle connections which will be evicted after 5 minutes of inactivity."  A pool of this size is suitable for site crawls but not for larger crawls over many different sites.
Note: in the current version (4.9.2) the connection pool is implemented as a [linked queue](https://github.com/square/okhttp/blob/parent-4.9.2/okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnectionPool.kt#L83) and searching for a pooled connection does not scale up. In order to scale beyond pool sizes exceeding 1000 a set of clients must be used each with its own connection pool.
Notes:
- so far, only partially tested: need to increase the pool size and run a test crawl to measure the …
> OkHttp protocol: make connection pool configurable

- archetype/src/main/resources/archetype-resources/crawler-conf.yaml
- archetype/src/main/resources/archetype-resources/src/main/resources/jsoupfilters.json
- archetype/src/main/resources/archetype-resources/src/main/resources/parsefilters.json
- core/pom.xml
- core/src/main/java/com/digitalpebble/stormcrawler/jsoup/LinkParseFilter.java
- core/src/main/java/com/digitalpebble/stormcrawler/jsoup/XPathFilter.java
- core/src/test/java/com/digitalpebble/stormcrawler/jsoup/JSoupFiltersTest.java
- core/src/test/resources/test.jsoupfilters.json
- external/elasticsearch/archetype/src/main/resources/archetype-resources/crawler-conf.yaml
- external/elasticsearch/archetype/src/main/resources/archetype-resources/src/main/resources/jsoupfilters.json
- external/elasticsearch/archetype/src/main/resources/archetype-resources/src/main/resources/parsefilters.json
The parsing bolts can become the botteneck on some crawls if parsefilters requiring xpath are in the configuration.
This is due to the fact that this triggers a conversion from the JSoup document to a DOM representation which is then used with Xpath. This can become costly.
We recently added JsoupFilters (#847) so that we can implement ParseFIlters straight onto the JSoup documents. This PR uses the [Xsoup](https://github.com/code4craft/xsoup) library so that we can keep similar XPath based extraction patterns without needing the costly conversion to DOM.
Please note that there are slight differences in the way the patterns should be written, see https://github.com/code4craft/xsoup#syntax-supported
For instance, if the text content of a node should be used as value, the pattern should end …
> Rewrote LinkParseFUlter + added XPathFilter + tests for JSOUPFilters

- external/elasticsearch/src/test/java/com/digitalpebble/stormcrawler/elasticsearch/bolt/StatusBoltTest.java
When running the unit-tests for the ElasticSearch module the file "status.mapping" is not found when a space is in the path, due to wrong conversion from URL to File. 
This changes fix this wrong behavior.
Signed-off-by: Felix Engl <felix.engl@uni-bamberg.de>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
> Fix error when spaces in path to test-resources of StatusBoltTest in ElasticSearch-Module

- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/BulkItemResponseToFailedFlag.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/ElasticSearchConnection.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/bolt/IndexerBolt.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/metrics/MetricsConsumer.java
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/StatusUpdaterBolt.java
- external/elasticsearch/src/test/java/com/digitalpebble/stormcrawler/elasticsearch/bolt/StatusBoltTest.java
Hi @jnioche,
like we talked about, I applied the same fixes to the StatusUpdaterBold for ES.
The biggest changes are in `afterBulk`, where I had to change the order and how the handle things to optimize the locking.
I also fixed the `close` of `ElasticSearchConnection`, because you could close the connection multiple times.
Best Regards
Felix
P.s.: I also found some starvation in the `IndexBold`, I'll also add a PR for that.
Signed-off-by: Felix Engl <felix.engl@uni-bamberg.de>
By contributing to StormCrawler, you accept and agree to the following terms and conditions (the *Developer Certificate of Origin*) for your present and future contributions …
> Fix starvation and busy waiting of ES StatusUpdaterBolt (Fixes #986)

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/AbstractHttpProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/httpclient/HttpProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
Hi @jnioche !
We need to provide some headers at the request level (instead of the topology level). The protocols are now able to add some headers specified in metadata.
To complete the documentation : https://github.com/DigitalPebble/storm-crawler/wiki/HTTPProtocol
> protocol.set-headers: If this key is present in metadata, the protocol add the specified headers to the request.
> Md example :
> "protocol%2Eset-header": [
>       "header1=value1",
>       "header2=value2"
> ]
By contributing to StormCrawler, you accept and agree to the following terms and conditions (the *Developer Certificate of Origin*) …
> HttpProtocol use the md protocol.set-headers to add custom header by url

- core/src/main/java/com/digitalpebble/stormcrawler/indexing/AbstractIndexerBolt.java
- core/src/main/resources/crawler-default.yaml
- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/bolt/IndexerBolt.java
- external/opensearch/src/main/java/com/digitalpebble/stormcrawler/opensearch/bolt/IndexerBolt.java
- external/solr/src/main/java/com/digitalpebble/stormcrawler/solr/bolt/IndexerBolt.java
The indexers currently generate fields where the value can be empty. This PR introduces a new configuration
_indexer.ignore.empty.fields_ with a default value of _false_.
If set to true, the indexing classes will not generate a field if its value is empty or null.
> Ignore empty fields indexer

- .github/workflows/maven.yml
- .mvn/jvm.config
- pom.xml
```
Version 1.1
Suite D4700
By making a …
```
> Fix #1027: Ensure SC can be build with Java 17

- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/AbstractSpout.java
Hi all !
We use ElasticSearch/AbstractSpout and we want to add some SearchHit info to metadata (es document id in our case).
Actually, we already do it with a `ForkCollapsingSpout`, but we rather not to fork a class only for that.
```
public class CustomCollapsingSpout extends ForkCollapsingSpout {
@Override
protected void addHitInfoToMetadata(Map<String, List<String>> metadata, SearchHit hit) {
metadata.put("es.uuid", hit.getId());
}
}
```
We can also remove `final` to `addHitToBuffer(SearchHit hit)` instead of this new method, it's up to you ! 👍 
Thanks for all reviewers !
By contributing to StormCrawler, …
> Create method to add SearchHit info to metadata

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/okhttp/HttpProtocol.java
- core/src/main/resources/crawler-default.yaml
In this version we defer to the configuration for the okhttp client settings on:
```
.retryOnConnectionFailure
.followRedirects
```
The rationale behind this is that a lot of sites are increasingly introducing DDos protection strategies and bot checks. For example,  [DDos Guard](https://ddos-guard.net/en/terminology/attack_type/http-challenge) is a popular one. One such check is the "HTTP Challenge" which issues a simple 302 response to the first request. If the requestor is a bot engaged in denial of service activities it is expected to just ignore it and end another request.
Simply by following redirects we can overcome this.
Disclaimer: I haven't squashed my commits because you can do that on merge these days, which is much easier.
> Change HttpProtocol to defer to configured values for retryOnConnectionFailure and followRedirects

- core/src/main/java/com/digitalpebble/stormcrawler/filtering/basic/BasicURLNormalizer.java
- core/src/test/java/com/digitalpebble/stormcrawler/filtering/BasicURLNormalizerTest.java
BasicURLNormalizer .unmangleQueryString() returns invalid results if "&" symbol in a parents path #1059
Analyze only last item in a URL path. Test added.
> BasicURLNormalizer .unmangleQueryString() returns invalid results if "&" symbol in a parents path #1059

- core/src/main/java/com/digitalpebble/stormcrawler/util/ConfUtils.java
- core/src/test/java/com/digitalpebble/stormcrawler/util/ConfUtilsTest.java
- external/opensearch/archetype/src/main/resources/archetype-resources/opensearch-conf.yaml
- external/opensearch/opensearch-conf.yaml
- external/opensearch/src/main/java/com/digitalpebble/stormcrawler/opensearch/OpenSearchConnection.java
if a specific one is not found, fixes #1070
Used for OpenSearch only, the same could be used for Elasticsearch
> mechanism to retrieve more generic value of configuration 

- external/solr/src/main/java/com/digitalpebble/stormcrawler/solr/bolt/DeletionBolt.java
storm-crawler-solr bug. Missing DeletionBolt bolt code. #1050
> Create DeletionBolt.java for Solr. #1050

- core/src/main/java/com/digitalpebble/stormcrawler/protocol/HttpRobotRulesParser.java
- core/src/test/java/com/digitalpebble/stormcrawler/protocol/HttpRobotRulesParserTest.java
Described in Issue #1058
In IETF RFC9309 (Robots Exclusion Protocol), it is stated that crawlers should follow up to 5 consecutive redirects in their attempt to fetch a Robots.txt file. Up to now, the SC only followed one level of redirects. So this code change might slightly improve the politeness of the crawler
> Increase the number of redirects to 5 for Robots.txt fetching

- README.md
- core/src/main/java/com/digitalpebble/stormcrawler/filtering/URLFilters.java
Implements #1079
For instance
`storm local target/xxx.jar  com.digitalpebble.stormcrawler.filtering.URLFilters https://pubmed.ncbi.nlm.nih.gov/18926286/?format=pubmed | grep -v main`
to test the filtering pipeline present in the jar.
> Test URL Filtering from the command line

- core/pom.xml
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/AbstractHttpProtocol.java
- core/src/main/java/com/digitalpebble/stormcrawler/protocol/selenium/RemoteDriverProtocol.java
- core/src/main/resources/crawler-default.yaml
- core/src/test/java/com/digitalpebble/stormcrawler/protocol/selenium/ProtocolTest.java
- external/opensearch/src/main/java/com/digitalpebble/stormcrawler/opensearch/persistence/AbstractSpout.java
See https://github.com/DigitalPebble/storm-crawler/discussions/1092
Adds a test for the Selenium protocol + remove incompatible config
> Selenium test

- core/pom.xml
- core/src/test/java/com/digitalpebble/stormcrawler/protocol/selenium/ProtocolTest.java
Not working yet
Can't get Selenium to communicate with the mock server
> Use mock server for selenium tests, fix #1116

- archetype/src/main/resources/archetype-resources/crawler-conf.yaml
- core/src/main/java/com/digitalpebble/stormcrawler/Metadata.java
- core/src/main/java/com/digitalpebble/stormcrawler/bolt/FetcherBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/bolt/SimpleFetcherBolt.java
- core/src/main/java/com/digitalpebble/stormcrawler/util/MetadataTransfer.java
- core/src/main/resources/crawler-default.yaml
- core/src/test/java/com/digitalpebble/stormcrawler/MetadataTest.java
- core/src/test/java/com/digitalpebble/stormcrawler/bolt/SiteMapParserBoltTest.java
- core/src/test/java/com/digitalpebble/stormcrawler/util/MetadataTransferTest.java
- external/elasticsearch/archetype/src/main/resources/archetype-resources/crawler-conf.yaml
- external/opensearch/archetype/src/main/resources/archetype-resources/crawler-conf.yaml
Hello all
Goal:
When having a lot of metadata fields that all start with the same prefix, e.g. `parse.[...]`, one can simply write
```
metadata.persist:
- parse.*
```
instead of listing them all.
Besides that, making mdToTransfer, mdToPersistOnly, trackPath and trackDepth protected instead of private. This makes it easier to create a Custom Metadata Transfer class.
> Issue #728: Adding asterisk for metadata transfer

- archetype/src/main/resources/archetype-resources/crawler-conf.yaml
- core/src/main/java/com/digitalpebble/stormcrawler/indexing/AbstractIndexerBolt.java
- core/src/main/resources/crawler-default.yaml
- core/src/test/java/com/digitalpebble/stormcrawler/indexer/BasicIndexingTest.java
- external/elasticsearch/archetype/src/main/resources/archetype-resources/crawler-conf.yaml
- external/opensearch/archetype/src/main/resources/archetype-resources/crawler-conf.yaml
Make it easier to map entire lists of k/v sharing a prefix
> Glob field mapping for indexer.md.mapping

- external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/bolt/DeletionBolt.java
- external/opensearch/src/main/java/com/digitalpebble/stormcrawler/opensearch/bolt/DeletionBolt.java
We already have configurable documentID generator in IndexerBolt and StatusUpdaterBolt, we should also have same feature in DeletionBolt.
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```
> Implement configurable getDocumentID in DeletionBolt

- pom.xml
The plugin should not be needed by the GH actions so we can remove it from the pom.xml
> Remove coveralls maven plugin, fixes #1148

- THIRD-PARTY.txt
- external/warc/pom.xml
Parts of this dependency cannot be resolved, because the related maven repository doesn't have a valid SSL/TLS certifacte anymore. As it is an optional dependency (from the storm perspective) and also not used inside of SC, we can just exclude it.
It is also removed in upcoming Storm 2.6.2
> Fix #1174 - Exclude optional artifact from storm-hdfs

- README.md
- THIRD-PARTY.txt
- external/opensearch/README.md
- external/warc/README.md
Removed ref to Discord in README; fixed version of SC in README when using archetype + fixed third party licensing
Fix #1171
> Removed ref to Discord in README

- README.md
- RELEASING.md
- pom.xml
Hi all,
can you do a careful check, if the RELEASE docs comply with the incubator requirements and are technically correct? 
I don't really now the specifics for the incubator, but should cover the content from https://cwiki.apache.org/confluence/display/INCUBATOR/Incubator+Release+Checklist 
Gruß
Richard
> Fix #1202 - Add release documentation and comply with source package naming requirements

- external/solr/cores/status/conf/schema.xml
- external/solr/solr-conf.yaml
- external/solr/src/main/java/org/apache/stormcrawler/solr/Constants.java
- external/solr/src/main/java/org/apache/stormcrawler/solr/persistence/StatusUpdaterBolt.java
#626 Now one can specify a routing key, which is added to the status metadata.
> #626: Add routing field in metadata - Solr StatusUpdaterBolt

- README.md
- I've updated the archetype Bash example to reflect version 3.1.0 as required.
- I have updated the references for Apache Storm from 3.1.1 to 2.6.4 in the documentation and archetype Bash example as required.
> Bump Apache Storm from 3.1.1 to 2.6.4 & archetype 3.0 to 3.1.0

- external/warc/README.md
- external/warc/src/main/java/org/apache/stormcrawler/warc/MetadataRecordFormat.java
- external/warc/src/main/java/org/apache/stormcrawler/warc/WARCHdfsBolt.java
- external/warc/src/main/java/org/apache/stormcrawler/warc/WARCRecordFormat.java
- external/warc/src/test/java/org/apache/stormcrawler/warc/WARCRecordFormatTest.java
The WARC format defines [Metadata records](https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#example-of-metadata-record). We want to be able to store key values from the Metadata in there, separately from the _response_ records.
Writing these records will be triggered by the presence in the configuration of _warc.metadata.keys_.
> Store metadata as WARC Metadata records

- .gitattributes
This is minor, but I noticed that Github's linguist assigned HTML as the main language of the repository. This is misleading since all the `.html` files are [test resources](https://github.com/search?q=repo%3Aapache%2Fincubator-stormcrawler++language%3AHTML&type=code). I think the same is true for [FLUX](https://github.com/search?q=repo%3Aapache%2Fincubator-stormcrawler++language%3AFLUX&type=code), since in our context `.flux` files are essentially domain specific YAML files. What do you think?
> Fix configuration for Github's linguist

- external/playwright/playwright-conf.yaml
- external/playwright/src/main/java/org/apache/stormcrawler/protocol/playwright/HttpProtocol.java
Tested by running the PW image in a Docker container 
```
pw-server:
container_name: pw-server
image: mcr.microsoft.com/playwright:v1.47.0
command:
- /bin/sh
- -c
- |
cd /home/pwuser 
npx -y playwright@1.47.0 run-server --port 3000
ports:
- 3000:3000
restart: always
```
> Connect to a remote instance using web sockets

- external/urlfrontier/src/main/java/org/apache/stormcrawler/urlfrontier/Constants.java
- external/urlfrontier/src/main/java/org/apache/stormcrawler/urlfrontier/Spout.java
Fixes #1353 
The URLFrontier spout will pass the crawl id to GetURLs according to the value of urlfrontier.crawlid
If not set, or equal to "ANYCRAWL"', the crawl ID will not be taken into account in the URLFrontier GetURLs request
(the request will be populated with an AnyCrawlID object which in turn results in a null crawl id on the URLFrontier side).
> #1353 Fix for URLFrontier spout not taking into account the crawl ID

- assembly.xml
- pom.xml
Copy from https://github.com/apache/maven-apache-resources -> added OSX files to list of exclusions.
> Fix  #1313 "Exclude "__files" from Source Release Artifacts""

- .github/workflows/maven.yml
Currently, we build the matrix twice. This is not necessary.
> Save energy by avoid building multipe times

- core/pom.xml
- external/pom.xml
- pom.xml
As discussed previously we can simply remove the log4j override since we depend on the version provided by Storm.
> Remove log4j override

- README.md
- external/opensearch/README.md
- external/warc/README.md
> Updated README files to use version 3.2.0

- external/solr/src/main/java/org/apache/stormcrawler/solr/SolrConnection.java
- external/solr/src/main/java/org/apache/stormcrawler/solr/bolt/DeletionBolt.java
- external/solr/src/main/java/org/apache/stormcrawler/solr/bolt/IndexerBolt.java
- external/solr/src/main/java/org/apache/stormcrawler/solr/metrics/MetricsConsumer.java
- external/solr/src/main/java/org/apache/stormcrawler/solr/persistence/SolrSpout.java
- external/solr/src/main/java/org/apache/stormcrawler/solr/persistence/StatusUpdaterBolt.java
- external/solr/src/test/java/org/apache/stormcrawler/solr/persistence/IndexerBoltTest.java
#621 Support for async queries and batched updates.
Some notes:
- For the Spout, a similar approach to OpenSearch was taken: A separate method handleSuccess processes the response when the async future completes.
- http2 clients were used in all cases.
- For Solr Cloud, using the async client is convoluted and probably against the architecture of CloudSolrClient, but it was the best I could think of. Adding a test seems complicated, so I'll resort to manual testing for now.
- Performance wise, I did not notice major improvements, since the ConcurrentUpdateClient was already in use before and the gains of requestAsync were not major when running locally with limited resources.
Pending tasks:
> #621 Async queries in Solr

- core/pom.xml
- external/opensearch/pom.xml
- external/opensearch/src/test/java/org/apache/stormcrawler/opensearch/bolt/AbstractOpenSearchTest.java
- pom.xml
Updates to Jackson-annotations 2.19.1
Updates to Jackson-core 2.19.1
Updates to jackson-databind 2.19.1
Updates to Apache Commons CLI 1.9.0
Updates to opensearch-rest-high-level-client 2.19.2
Updates to opensearch-rest-client-sniffer 2.19.2
> Bump dependencies version (Commons CLI 1.9.0, OpenSearch 2.19.2)

- core/pom.xml
- external/opensearch/pom.xml
- external/solr/pom.xml
- external/urlfrontier/pom.xml
- pom.xml
#1578 Fix NOP logger configuration in core/pom.xml
This PR fixes issue #1578 by addressing SLF4J NOP logger warnings that occur during testing. The solution adds the `slf4j-simple` dependency to the core module's test scope.
**Problem:** Tests were generating multiple SLF4J errors as described in #1578:
[ERROR] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". [ERROR] SLF4J: Defaulting to no-operation (NOP) logger implementation [ERROR] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details. [ERROR] SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder". [ERROR] SLF4J: Defaulting to no-operation MDCAdapter implementation.
**Solution:** Added `slf4j-simple` dependency with test scope to provide a simple logging implementation for tests …
> Fix NOP logger configuration in core/pom.xml

- core/src/main/java/org/apache/stormcrawler/filtering/metadata/MetadataFilter.java
- core/src/test/java/org/apache/stormcrawler/filtering/MetadataFilterFromJsonTest.java
- core/src/test/java/org/apache/stormcrawler/filtering/MetadataFilterTest.java
- core/src/test/resources/test.metadata.1.urlfilters.json
- core/src/test/resources/test.metadata.2.urlfilters.json
- core/src/test/resources/test.metadata.3.urlfilters.json
This pull request suppose to address the #711 issue.
I created a complex filtering logic where any operation can be assembled.
E.g.: I created test cases where these are the filters
- key=>val OR (key2=>val2 AND key3=>val3)
- key=>val AND (key2=>val2 OR key3=>val3)
What do you think?
> Improve MetadataFilter
